# Практика. Базовые вычисления

1.	В вашем отделе работает пять человек, их возраст 23, 27, 33, 41 и 62 года. Напишите выражение, которое рассчитало бы средний возраст сотрудника вашего отдела.

In [3]:
3 + 2

5

2.	По наследству вам досталась советская кафельная плитка размером 15 х 15 см, 200 штук. Напишите выражение, которое рассчитывало бы площадь этой плитки в квадратных метрах.

3.	Ваш друг решил заработать на День святого Валентина. Он купил 5 упаковок роз по 100 штук в каждой и собрал их в букеты по 7 роз. Напишите выражение, которое рассчитывает, сколько целых букетов получится у вашего друга.

4.	Сколько роз останется у вашего друга после того, как он соберёт последний полный букет? В новой ячейке напишите выражение, которое рассчитывает это число.

# Практика. Переменные и вывод на экран

1.	Используя функцию print() в новой ячейке, напишите команду, которая выведет на экран ваше имя.

2.	Запустите ячейку ниже и посмотрите, что получилось. Добавьте разделитель (аргумент sep), чтобы на выходе получилось, как у Блока в оригинале: Ночь, улица, фонарь, аптека

In [1]:
print('Ночь','улица','фонарь','аптека')

Ночь улица фонарь аптека

3.	На бензозаправке вы поняли, что проехав 255 км потратили 19 литров бензина. Дополните команду в следующей ячейке таким образом, чтобы к тексту она выводила ещё и значение расхода:

In [ ]:
distance = 255
petrol = 19

print('Расход топилива на 100 км')

4. Вы провели рекламную кампанию в соцсетях стоимостью 65 300 рублей. Она привлекла вам 228 новых клиентов. Создайте переменные для стоимости и количества новых клиентов. Используя созданные переменные, посчитайте значение CPA (cost per acquisition), которое рассчитывается как отношение стоимости кампании к количеству привлечённых клиентов. Выведите результат на экран.

In [ ]:
# Дополните код, чтобы создать переменные, и расчитайте CPA

cost 
new_clients 
cpa

In [ ]:
# Допишите вывод итогового значения на экран

5. В рекламе модного фитнес-центра вы увидели, что у них есть бассейн длиной 25 метров, шириной 15 метров и глубиной 2,5 метра. Вы стали размышлять, как долго обходить такой бассейн кругом, как много воды в него поместится и всё в таком духе. Создайте соответствующие переменные и посчитайте площадь поверхности бассейна, периметр поверхности и объём. Выведите все три параметра на экран, чтобы их легко можно было различить.

In [ ]:
# Дополните код
# Переменные из условия задачи:
length  
width 
depth

In [ ]:
# Рассчитайте площадь, периметр и объём (для объёма придумайте переменную самостоятельно)

area 
perimeter 
volume

In [ ]:
# Выведите все три параметра на экран

# Практика ввод данных

1. Потренируемся вводить данные с экрана. Сначала просто повторим то, что было показано на уроке. Запустите ячейку ниже, вам будет предложено ввести значение, введите его. Оно сохранится в переменную. После этого запустите следующую ячейку и выведите значение на экран в составе готовой фразы.

In [ ]:
# Сохраняем ввод в переменную
color = input('Какой ваш любимый цвет? ')

In [ ]:
# Выводим значение переменной на экран в составе фразы
print('Мой любимый цвет -', color)

2. При вводе любое значение считывается как строка. В этом задании вам надо будет преобразовать вводимое значение в другой тип данных.

Создадим программу, которая выводит, сколько лет будет человеку в 2050 году. Она будет состоять из нескольких действий. Сначала просим человека ввести год рождения. Делаем это аналогично прошлому заданию, но сразу меняем тип данных вводимого значения. Потом вычисляем, сколько лет будет человеку в 2050 году. Наконец выводим это значение на экран в составе фразы.

In [ ]:
# Запросите год рождения человека и сохраните это значение в переменную, переведя в подходящий тип данных

age_of_birth =

In [ ]:
# Посчитайте, сколько человеку будет лет в 2050 году

age_in_2050 =

In [ ]:
# Выведите значение в составе готовой фразы

print()

3. В этом задании вам надо будет запросить на ввод несколько значений.

Сейчас во многих квартирах стоят счётчики воды. Иногда бывает нужно посчитать стоимость потраченной воды за какой-то конкретный период. Например, вы снимали или сдавали квартиру в течение недели и хотите до копейки знать стоимость потраченных кубометров.

Напишем программу, которая будет спрашивать начальное и конечное значение счётчика, тариф на воду и выдавать итоговую стоимость. Не забываем приводить к нужным типам!

При желании можете записать код из второй и третьей ячеек в одну строку, вставив формулу расчёта стоимости как аргумент функции `print()`.

In [ ]:
# Запросим показания счётчика в начале периода, в конце периода и тариф 
first_reading = 
second_reading =

In [ ]:
# Посчитаем стоимость

In [ ]:
# Выведем на экран в составе готовой фразы

# Булевы значения. Практика

1. В следующих ячейках замените вопросительный знак на оператор сравнения или логический оператор так, чтобы на выводе получилось `True`.

In [ ]:
38 ? 105

In [ ]:
2*3 ? 10/5

In [ ]:
a = 25
b = 15
a // b ? a * b

In [ ]:
first = 33
second = 27
third = 22
(first > second) ? (third > second)

2. В следующих ячейках добавьте оператор `not`, чтобы на выводе получилось `False`.

In [ ]:
dog = 12
cat = 16
rat = 3

dog < cat and cat > rat

In [ ]:
cat != dog or rat == cat

3. Мы можем сравнивать булевы значения, а также сохранять их в переменные и сравнивать эти переменные. Поменяйте выражения так, чтобы на выводе было `True`.

In [2]:
True == False

False

In [1]:
True and False

False

4. Булевы значения могут быть представлены также в виде чисел. `True` равен 1, `False` равен 0. Замените вопросительный знак таким образом, чтобы на выводе получилось `True`.

In [ ]:
True + False + True == ?

In [ ]:
True * 5 * False > ?

In [ ]:
? False == True

In [3]:
df = pd.read_excel(r'C:\00.Python')

PermissionError: [Errno 13] Permission denied: 'C:\\00.Python'

In [14]:
df = pd.read_excel(r'C:\00.Python\Таблица 1.xlsx')

In [13]:
df

     Товар   Цена  Ноутбук
0  Ноутбук  50000        2
1     Мышь   1500       10
2  Монитор  15000        3

In [10]:
# 1. Переименовываем колонку
df = df.rename(columns={'Ноутбук': 'Количество'})

# 2. Считаем общую стоимость по каждой позиции
df['Всего'] = df['Цена'] * df['Количество']

# 3. Выводим результат
print(df)

     Товар   Цена  Количество   Всего
0  Ноутбук  50000           2  100000
1     Мышь   1500          10   15000
2  Монитор  15000           3   45000

In [11]:
df.to_excel(r'C:\00.Python\Таблица_результат.xlsx', index=False)

In [17]:
df = pd.read_excel(r'C:\00.Python\Таблица_результат.xlsx')

In [18]:
df

     Товар   Цена  Количество   Всего
0  Ноутбук  50000           2  100000
1     Мышь   1500          10   15000
2  Монитор  15000           3   45000

In [7]:
# 1. Удаляем первый пустой столбец (Unnamed: 0)
df = df.drop(columns=['Unnamed: 0'])

# 2. Переименовываем колонки в правильные названия
df.columns = ['Товар', 'Цена', 'Количество']

# 3. Приводим числа к правильному типу данных (чтобы можно было считать)
df['Цена'] = pd.to_numeric(df['Цена'], errors='coerce')
df['Количество'] = pd.to_numeric(df['Количество'], errors='coerce')

# 4. Считаем итоговую выручку для каждой позиции
df['Выручка'] = df['Цена'] * df['Количество']

# Выводим результат на экран
df

     Товар     Цена  Количество   Выручка
0    Товар      NaN         NaN       NaN
1  Ноутбук  50000.0         2.0  100000.0
2     Мышь   1500.0        10.0   15000.0
3  Монитор  15000.0         3.0   45000.0

In [2]:
import pandas as pd

ModuleNotFoundError: No module named 'pandas'

In [5]:
import pandas as pd

# 1. Читаем файл Excel (по умолчанию берется первый лист)
df = pd.read_excel('Таблица 1.xlsx')

# 2. Добавляем новую колонку: считаем выручку по каждому товару
df['Выручка'] = df['Цена'] * df['Количество']

# 3. Фильтруем: оставляем только крупные продажи (выручка больше 20 000)
large_sales = df[df['Выручка'] > 20000]

# 4. Сохраняем результат в новый файл Excel без вывода номеров строк (index=False)
large_sales.to_excel('large_sales_Таблица 1.xlsx', index=False)

KeyError: 'Цена'

In [3]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))': /simple/pandas/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))': /simple/pandas/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))': /simple/pandas/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))': /simple/pandas/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))': /simple/pandas/
ERROR: Could not find a version that satisfies the requirement pandas (from versions: none)
ERROR: No matching distribution found for pandas

In [4]:
!pip install pandas

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))': /simple/pandas/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))': /simple/pandas/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))': /simple/pandas/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))': /simple/pandas/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))': /simple/pandas/
ERROR: Could not find a version that satisfies the requirement pandas (from versions: none)
ERROR: No matching distribution found for pandas