# Модули и библиотеки. Основы Pandas

Содержание :
> [1. Подключение модулей](#modules) \
[2. Подключение библиотеки и чтение данных из файла](#pandas) \
[3. Методы loc и iloc для доступа к данным датасета](#loc_iloc) \
[4. Фильтрация данных по условию](#filter) \
[5. Сохранение в файл](#output) \
[6. Применение агрегирующих функций](#agregat) \
[7. Группировка данных](#groupby)

In [23]:
def add (a: int, b: int):
    return a + b

result = add (5, 5)
print(result)

10

In [24]:
def add_2 (c: int, d: int):
    return c * d

result_2 = add_2 (3, 3)
print(result_2)

9

# <a id="modules">1. Подключение модулей</a>

In [25]:
import add

4

In [94]:
result = add.add(5, 5)
print(result)

10

Модули – это файлы Python, содержащие функции, переменные или классы.
У python есть встроенные модули, их очень много, они покрывают разные задачи. Вот несколько популярных с примерами задач:
1.	Модуль `math` — для математических операций.
Задача: найти корень из числа, вычислить факториал.
2.	Модуль `datetime` — для работы с датами и временем.
Задача: вывести текущую дату и время, посчитать разницу между датами.
3.	Модуль `random` — генерация случайных чисел.
Задача: сгенерировать случайное число, перемешать элементы списка.
4.	Модуль `os` — взаимодействие с операционной системой.
Задача: получить список файлов в папке, создать новый каталог.
5.	Модуль `sys` — взаимодействие с интерпретатором Python и его параметрами.
Задача: получить аргументы командной строки, завершить программу с кодом ошибки.
6.	Модуль `csv` — чтение и запись CSV-файлов.
Задача: считать данные из CSV и вывести их, сохранить данные в CSV.
7.	Модуль `collections` — специализированные структуры данных.
Задача: подсчет количества элементов с помощью Counter.
8.	Модуль `itertools` — функции для работы с итераторами.
Задача: объединить несколько списков подряд.

In [5]:
import math

In [6]:
print(dir(math))

['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'cbrt', 'ceil', 'comb', 'copysign', 'cos', 'cosh', 'degrees', 'dist', 'e', 'erf', 'erfc', 'exp', 'exp2', 'expm1', 'fabs', 'factorial', 'floor', 'fma', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'isqrt', 'lcm', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'nextafter', 'perm', 'pi', 'pow', 'prod', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'sumprod', 'tan', 'tanh', 'tau', 'trunc', 'ulp']

In [10]:
help(math.__doc__)

No Python documentation found for 'This module provides access to the mathematical functions\ndefined by the C standard.'.
Use help() to get the interactive help utility.
Use help(str) for help on the str class.

In [96]:
a = math.sqrt(15)
print(a)

3.872983346207417

In [6]:
# вызов функции из модуля
from math import sqrt

a = sqrt(9)
a

3.0

In [11]:
from math import sqrt

b = sqrt(625)
b

25.0

In [14]:
from math import degrees

print(degrees(3.14159))

179.9998479605043

In [7]:
# Просмотр состава функций

dir(math)

['__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'cbrt',
 'ceil',
 'comb',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'dist',
 'e',
 'erf',
 'erfc',
 'exp',
 'exp2',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fma',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'isqrt',
 'lcm',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'nextafter',
 'perm',
 'pi',
 'pow',
 'prod',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'sumprod',
 'tan',
 'tanh',
 'tau',
 'trunc',
 'ulp']

In [ ]:
help(degrees)

NameError: name 'degrees' is not defined

In [15]:
# Вызов функции из модуля
help(math.sin)

Help on built-in function sin in module math:

sin(x, /)
    Return the sine of x (measured in radians).

In [16]:
# Находим синус 30 градусов
ugol_gradusy = 30
ugol_radiany = math.radians(ugol_gradusy)  # переводим в радианы

result = math.sin(ugol_radiany)
print(result)  # Выведет: 0.49999999999999994 (то есть примерно 0.5)

0.49999999999999994

In [18]:
help(math.remainder)

Help on built-in function remainder in module math:

remainder(x, y, /)
    Difference between x and the closest integer multiple of y.

    Return x - n*y where n*y is the closest integer multiple of y.
    In the case where x is exactly halfway between two multiples of
    y, the nearest even value of n is used. The result is always exact.

In [17]:
8 % 3

2

In [10]:
math.remainder(8, 3)

-1.0

In [20]:
# Применение псевдонимов
import math as m

print(m.sqrt(25))

5.0

# Модуль random 
Этот модуль используется для генерации случайных чисел и данных. Это может быть полезно для различных сценариев, например, случайный выбор элементов или создание случайных чисел.

**Задача 1. Случайное число в заданном диапазоне** \
Сгенерировать и вывести случайное число от 1 до 10 \
`random.randint(a, b)` - случайное целое число n, a ≤ n ≤ b.

In [22]:
import random

In [40]:
for i in range (5):
    num = random.randint(1,100)
    print(f'Случайное число от 1 до 100: {num}')

Случайное число от 1 до 100: 18
Случайное число от 1 до 100: 60
Случайное число от 1 до 100: 50
Случайное число от 1 до 100: 12
Случайное число от 1 до 100: 92

In [33]:
num = random.randint(1, 100)
print(f'Случайное число от 1 до 100: {num}')

Случайное число от 1 до 100: 89

In [ ]:
import random

for i in range (120):
    num_win = random

In [43]:
#Симулятор рулетки на Python
import random

# Создаем список всех возможных исходов на европейской рулетке
# (число и его цвет в виде кортежа)
roulette_numbers = [("0", "зеленый")] + \
                   [(str(x), "красный") for x in [1,3,5,7,9,12,14,16,18,19,21,23,25,27,30,32,34,36]] + \
                   [(str(x), "черный") for x in [2,4,6,8,10,11,13,15,17,20,22,24,26,28,29,31,33,35]]

# Крутим рулетку!
winning_sector = random.choice(roulette_numbers)

number, color = winning_sector
print(f"Шарик упал на: {number} ({color})")

Шарик упал на: 34 (красный)

In [59]:
#Программа принимает ставку через поле ввода, крутит рулетку и считает баланс игрока
import random

# Стартовый баланс монет
balance = 1000

# Множества для проверки цветов
red_numbers = {1, 3, 5, 7, 9, 12, 14, 16, 18, 19, 21, 23, 25, 27, 30, 32, 34, 36}
black_numbers = {2, 4, 6, 8, 10, 11, 13, 15, 17, 20, 22, 24, 26, 28, 29, 31, 33, 35}

print("🎰 Добро пожаловать в Python-рулетку!")
print("Вы можете ставить на: 'красное', 'черное', на конкретное число (0-36) или написать 'выход' для завершения игры.\n")

# Главный бесконечный цикл игры
while balance > 0:
    print("-" * 50)
    print(f"💰 Ваш текущий баланс: {balance} монет.")
    
    # 1. Принимаем ставку от пользователя
    bet_type = input("На что ставим? (красное / черное / число / выход): ").strip().lower()
    
    # Проверяем, хочет ли игрок выйти
    if bet_type == "выход":
        print(f"\n👋 Спасибо за игру! Вы уносите с собой {balance} монет.")
        break
        
    # Проверяем корректность типа ставки
    if bet_type not in ["красное", "черное"] and not (bet_type.isdigit() and 0 <= int(bet_type) <= 36):
        print("❌ Неверный тип ставки! Попробуйте еще раз.")
        continue

    # 2. Принимаем сумму ставки
    bet_amount_str = input(f"Сколько монет ставим? (1-{balance}): ").strip()
    if not bet_amount_str.isdigit():
        print("❌ Пожалуйста, введите число монет!")
        continue
        
    bet_amount = int(bet_amount_str)

    # Проверяем, хватает ли денег
    if bet_amount > balance or bet_amount <= 0:
        print(f"❌ Недостаточно монет или неверная сумма! У вас есть только {balance}.")
        continue

    # 3. Крутим рулетку
    winning_number = random.randint(0, 36)
    
    if winning_number == 0:
        winning_color = "зеленый"
    elif winning_number in red_numbers:
        winning_color = "красный"
    else:
        winning_color = "черный"
        
    print(f"\n🔮 Шарик крутится... и выпадает: {winning_number} ({winning_color})!")

    # 4. Проверяем логику выигрыша
    is_win = False
    payout_multiplier = 0

    if bet_type == "красное" and winning_color == "красный":
        is_win = True
        payout_multiplier = 2
    elif bet_type == "черное" and winning_color == "черный":
        is_win = True
        payout_multiplier = 2
    elif bet_type.isdigit() and int(bet_type) == winning_number:
        is_win = True
        payout_multiplier = 36

    # 5. Считаем итоги раунда
    if is_win:
        win_coins = bet_amount * (payout_multiplier - 1)
        balance += win_coins
        print(f"🎉 Вы выиграли {win_coins} монет!")
    else:
        balance -= bet_amount
        print(f"😢 Вы проиграли {bet_amount} монет.")

# Этот код сработает, когда баланс станет равен 0 и цикл прервется
if balance <= 0:
    print("-" * 50)
    print("💸 Упс! Ваши монеты закончились. Игра окончена!")

🎰 Добро пожаловать в Python-рулетку!
Вы можете ставить на: 'красное', 'черное', на конкретное число (0-36) или написать 'выход' для завершения игры.

--------------------------------------------------
💰 Ваш текущий баланс: 1000 монет.

🔮 Шарик крутится... и выпадает: 7 (красный)!
🎉 Вы выиграли 1000 монет!
--------------------------------------------------
💰 Ваш текущий баланс: 2000 монет.

🔮 Шарик крутится... и выпадает: 24 (черный)!
😢 Вы проиграли 1000 монет.
--------------------------------------------------
💰 Ваш текущий баланс: 1000 монет.
❌ Неверный тип ставки! Попробуйте еще раз.
--------------------------------------------------
💰 Ваш текущий баланс: 1000 монет.

🔮 Шарик крутится... и выпадает: 32 (красный)!
😢 Вы проиграли 500 монет.
--------------------------------------------------
💰 Ваш текущий баланс: 500 монет.

🔮 Шарик крутится... и выпадает: 3 (красный)!
😢 Вы проиграли 100 монет.
--------------------------------------------------
💰 Ваш текущий баланс: 400 монет.

🔮 Шарик крутится... и выпадает: 36 (красный)!
🎉 Вы выиграли 400 монет!
--------------------------------------------------
💰 Ваш текущий баланс: 800 монет.

🔮 Шарик крутится... и выпадает: 14 (красный)!
🎉 Вы выиграли 400 монет!
--------------------------------------------------
💰 Ваш текущий баланс: 1200 монет.

🔮 Шарик крутится... и выпадает: 3 (красный)!
😢 Вы проиграли 700 монет.
--------------------------------------------------
💰 Ваш текущий баланс: 500 монет.

🔮 Шарик крутится... и выпадает: 15 (черный)!
🎉 Вы выиграли 500 монет!
--------------------------------------------------
💰 Ваш текущий баланс: 1000 монет.

🔮 Шарик крутится... и выпадает: 30 (красный)!
🎉 Вы выиграли 1000 монет!
--------------------------------------------------
💰 Ваш текущий баланс: 2000 монет.

🔮 Шарик крутится... и выпадает: 24 (черный)!
😢 Вы проиграли 2000 монет.
--------------------------------------------------
💸 Упс! Ваши монеты закончились. Игра окончена!

**Задача 2. Случайный выбор из списка** \
Дан список цветов, случайным образом выбрать и вывести один из них. \
`random.choice(sequence)` - случайный элемент непустой последовательности.

In [15]:
colors = ['красный', 'синий', 'зеленый', 'жёлтый']
chosen_color = random.choice(colors)
print(f'Выбранный цвет: {chosen_color}')

Выбранный цвет: зеленый

**Задача 3. Перемешивание списка**
Дан список чисел, перемешать его элементы в случайном порядке и вывести. \
`random.shuffle(sequence)` - перемешивает последовательность (изменяется сама последовательность). Функция не работает для неизменяемых объектов.

In [16]:
numbers = [1, 2, 3, 4, 5]
random.shuffle(numbers)
print(f'Перемешанный список: {numbers}')

Перемешанный список: [2, 1, 5, 4, 3]

**Задача 4. Случайная выборка из списка без повторений**
Дан список имен, выбрать случайно 3 имени без повторений. \
`random.sample(population, k)` - список длиной k из последовательности population.

In [17]:
names = ['Аня','Борис','Вика','Гриша','Дима']
selected_names = random.sample(names, 3)
print(f'Выбранные имена: {selected_names}')

Выбранные имена: ['Гриша', 'Вика', 'Борис']

# Модуль os

**Задача 1. Определение текущей рабочей директории**

Получить и вывести путь текущей директории.

In [18]:
import os

In [19]:
current_dir = os.getcwd()
print("Текущая директория:", current_dir)

Текущая директория: c:\00.Python\Модуль 7_0

**Задача 2. Создание и удаление директории**

Создать новую директорию и затем удалить ее.

In [20]:
os.mkdir("new_folder") # создание папки
print("Создана папка 'new_folder'")

Создана папка 'new_folder'

In [21]:
os.rmdir("new_folder") # удаление папки
print("Папка 'new_folder' удалена")

Папка 'new_folder' удалена

**Задача 3. Проверка существования файла или папки**

Проверить, существует ли файл или директория

In [22]:
path = "example.txt"
if os.path.exists(path):
    print(f"{path} существует")
else:
    print(f"{path} не найден")

example.txt не найден

**Задача 4. Список всех файлов и директорий в папке**

Получить и вывести список файлов и папок в указанной директории.

In [23]:
files = os.listdir(".")
print("Содержимое текущей директории:", files)

Содержимое текущей директории: ['add.py', 'athlete_events.csv', 'partner_data.csv', 'partner_data.xlsx', 'partner_data_semicolon.csv', '__pycache__', 'Итоговая работа_М7.ipynb', 'Модуль 7.ipynb']

**Задача 5. Работа с путями: объединение и получение абсолютного пути**

Объединить несколько компонентов пути и получить абсолютный путь.

In [24]:
path = os.path.join("folder", "subfolder", "file.txt")
abs_path = os.path.abspath(path)
print("Относительный путь:", path)
print("Абсолютный путь:", abs_path)

Относительный путь: folder\subfolder\file.txt
Абсолютный путь: c:\00.Python\Модуль 7_0\folder\subfolder\file.txt

# Библиотеки

Библиотека – это набор модулей, классов и функций, которые собраны для выполнения определённой задачи.

При установке Python вы получаете большой набор встроенных модулей, которые можно импортировать в свой код. Стандартной библиотеке Python посвящён целый раздел документации https://docs.python.org/3/library/

# Основы pandas

**pandas** — программная библиотека на языке Python для обработки и анализа данных.

Установка и импорт библиотеки pandas в Jupyter Notebook:

In [25]:
#для информации (справочно есть еще Numpy - специализируется на числовых массивах)
%pip install pandas

Requirement already satisfied: pandas in C:\Users\UdovenkoDV\AppData\Roaming\Python\Python314\site-packages (3.0.2)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\UdovenkoDV\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\UdovenkoDV\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\UdovenkoDV\AppData\Roaming\Python\Python314\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\UdovenkoDV\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [26]:
#для информации 
%pip install openpyxl

Requirement already satisfied: openpyxl in C:\Users\UdovenkoDV\AppData\Roaming\Python\Python314\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in C:\Users\UdovenkoDV\AppData\Roaming\Python\Python314\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

# <a id="pandas">2. Подключение библиотеки и чтение данных из файла</a>

In [29]:
# Подключаем библиотеку
import pandas as pd

За чтение файлов форматов Excel, таких как xlsx, xls, odf и других, отвечает функция `pd.read_excel()` \
Документация по `pd.read_excel`: https://pandas.pydata.org/docs/reference/api/pandas.read_excel.html

In [30]:
help(pd.read_excel)

Help on function read_excel in module pandas:

read_excel(
    io,
    sheet_name: str | int | list[IntStrT] | None = 0,
    *,
    header: int | Sequence[int] | None = 0,
    names: SequenceNotStr[Hashable] | range | None = None,
    index_col: int | str | Sequence[int] | None = None,
    usecols: int | str | Sequence[int] | Sequence[str] | Callable[[HashableT], bool] | None = None,
    dtype: DtypeArg | None = None,
    engine: Literal['xlrd', 'openpyxl', 'odf', 'pyxlsb', 'calamine'] | None = None,
    converters: dict[str, Callable] | dict[int, Callable] | None = None,
    true_values: Iterable[Hashable] | None = None,
    false_values: Iterable[Hashable] | None = None,
    skiprows: Sequence[int] | int | Callable[[int], object] | None = None,
    nrows: int | None = None,
    na_values=None,
    keep_default_na: bool = True,
    na_filter: bool = True,
    verbose: bool = False,
    parse_dates: list | dict | bool = False,
    date_format: dict[Hashable, str] | str | None = None,
    thousands: str | None = None,
    decimal: str = '.',
    comment: str | None = None,
    skipfooter: int = 0,
    storage_options: StorageOptions | None = None,
    dtype_backend: DtypeBackend | lib.NoDefault = <no_default>,
    engine_kwargs: dict | None = None
) -> DataFrame | dict[IntStrT, DataFrame]
    Read an Excel file into a ``DataFrame``.

    Supports `xls`, `xlsx`, `xlsm`, `xlsb`, `odf`, `ods` and `odt` file extensions
    read from a local filesystem or URL. Supports an option to read
    a single sheet or a list of sheets.

    Parameters
    ----------
    io : str, ExcelFile, xlrd.Book, path object, or file-like object
        Any valid string path is acceptable. The string could be a URL. Valid
        URL schemes include http, ftp, s3, and file. For file URLs, a host is
        expected. A local file could be: ``file://localhost/path/to/table.xlsx``.

        If you want to pass in a path object, pandas accepts any ``os.PathLike``.

        By file-like object, we refer to objects with a ``read()`` method,
        such as a file handle (e.g. via builtin ``open`` function)
        or ``StringIO``.

    sheet_name : str, int, list, or None, default 0
        Strings are used for sheet names. Integers are used in zero-indexed
        sheet positions (chart sheets do not count as a sheet position).
        Lists of strings/integers are used to request multiple sheets.
        When ``None``, will return a dictionary containing DataFrames for each sheet.

        Available cases:

        * Defaults to ``0``: 1st sheet as a `DataFrame`
        * ``1``: 2nd sheet as a `DataFrame`
        * ``"Sheet1"``: Load sheet with name "Sheet1"
        * ``[0, 1, "Sheet5"]``: Load first, second and sheet named "Sheet5"
          as a dict of `DataFrame`
        * ``None``: Returns a dictionary containing DataFrames for each sheet.

    header : int, list of int, default 0
        Row (0-indexed) to use for the column labels of the parsed
        DataFrame. If a list of integers is passed those row positions will
        be combined into a ``MultiIndex``. Use None if there is no header.
    names : array-like, default None
        List of column names to use. If file contains no header row,
        then you should explicitly pass header=None.
    index_col : int, str, list of int, default None
        Column (0-indexed) to use as the row labels of the DataFrame.
        Pass None if there is no such column.  If a list is passed,
        those columns will be combined into a ``MultiIndex``.  If a
        subset of data is selected with ``usecols``, index_col
        is based on the subset.

        Missing values will be forward filled to allow roundtripping with
        ``to_excel`` for ``merged_cells=True``. To avoid forward filling the
        missing values use ``set_index`` after reading the data instead of
        ``index_col``.
    usecols : str, list-like, or callable, default None
        * If None, then parse all columns.
        * If str, then indicates comma separated list of Excel column letters
          and column ranges (e.g. "A:E" or "A,C,E:F"). Ranges are inclusive of
          both sides.
        * If list of int, then indicates list of column numbers to be parsed
          (0-indexed).
        * If list of string, then indicates list of column names to be parsed.
        * If callable, then evaluate each column name against it and parse the
          column if the callable returns ``True``.

        Returns a subset of the columns according to behavior above.
    dtype : Type name or dict of column -> type, default None
        Data type for data or columns. E.g. {'a': np.float64, 'b': np.int32}
        Use ``object`` to preserve data as stored in Excel and not interpret dtype,
        which will necessarily result in ``object`` dtype.
        If converters are specified, they will be applied INSTEAD
        of dtype conversion.
        If you use ``None``, it will infer the dtype of each column based on the data.
    engine : {'openpyxl', 'calamine', 'odf', 'pyxlsb', 'xlrd'}, default None
        If io is not a buffer or path, this must be set to identify io.
        Engine compatibility :

        - ``openpyxl`` supports newer Excel file formats.
        - ``calamine`` supports Excel (.xls, .xlsx, .xlsm, .xlsb)
          and OpenDocument (.ods) file formats.
        - ``odf`` supports OpenDocument file formats (.odf, .ods, .odt).
        - ``pyxlsb`` supports Binary Excel files.
        - ``xlrd`` supports old-style Excel files (.xls).

        When ``engine=None``, the following logic will be used to determine the engine:

        - If ``path_or_buffer`` is an OpenDocument format (.odf, .ods, .odt),
          then `odf <https://pypi.org/project/odfpy/>`_ will be used.
        - Otherwise if ``path_or_buffer`` is an xls format, ``xlrd`` will be used.
        - Otherwise if ``path_or_buffer`` is in xlsb format, ``pyxlsb`` will be used.
        - Otherwise ``openpyxl`` will be used.

    converters : dict, default None
        Dict of functions for converting values in certain columns. Keys can
        either be integers or column labels, values are functions that take one
        input argument, the Excel cell content, and return the transformed
        content.
    true_values : list, default None
        Values to consider as True.
    false_values : list, default None
        Values to consider as False.
    skiprows : list-like, int, or callable, optional
        Line numbers to skip (0-indexed) or number of lines to skip (int) at the
        start of the file. If callable, the callable function will be evaluated
        against the row indices, returning True if the row should be skipped and
        False otherwise. An example of a valid callable argument would be ``lambda
        x: x in [0, 2]``.
    nrows : int, default None
        Number of rows to parse. Does not include header rows.
    na_values : scalar, str, list-like, or dict, default None
        Additional strings to recognize as NA/NaN. If dict passed, specific
        per-column NA values. By default the following values are interpreted
        as NaN: '', '#N/A', '#N/A N/A', '#NA', '-1.#IND', '-1.#QNAN', '-NaN', '-nan',
        '1.#IND', '1.#QNAN', '<NA>', 'N/A', 'NA', 'NULL', 'NaN', 'None',
        'n/a', 'nan', 'null'.
    keep_default_na : bool, default True
        Whether or not to include the default NaN values when parsing the data.
        Depending on whether ``na_values`` is passed in, the behavior is as follows:

        * If ``keep_default_na`` is True, and ``na_values`` are specified,
          ``na_values`` is appended to the default NaN values used for parsing.
        * If ``keep_default_na`` is True, and ``na_values`` are not specified, only
          the default NaN values are used for parsing.
        * If ``keep_default_na`` is False, and ``na_values`` are specified, only
          the NaN values specified ``na_values`` are used for parsing.
        * If ``keep_default_na`` is False, and ``na_values`` are not specified, no
          strings will be parsed as NaN.

        Note that if `na_filter` is passed in as False, the ``keep_default_na`` and
        ``na_values`` parameters will be ignored.
    na_filter : bool, default True
        Detect missing value markers (empty strings and the value of na_values). In
        data without any NAs, passing ``na_filter=False`` can improve the
        performance of reading a large file.
    verbose : bool, default False
        Indicate number of NA values placed in non-numeric columns.
    parse_dates : bool, list-like, or dict, default False
        The behavior is as follows:

        * ``bool``. If True -> try parsing the index.
        * ``list`` of int or names. e.g. If [1, 2, 3] -> try parsing columns 1, 2, 3
          each as a separate date column.
        * ``list`` of lists. e.g.  If [[1, 3]] -> combine columns 1 and 3 and parse as
          a single date column.
        * ``dict``, e.g. {'foo' : [1, 3]} -> parse columns 1, 3 as date and call
          result 'foo'

        If a column or index contains an unparsable date, the entire column or
        index will be returned unaltered as an object data type. If you don`t want to
        parse some cells as date just change their type in Excel to "Text".
        For non-standard datetime parsing, use ``pd.to_datetime`` after
        ``pd.read_excel``.

        Note: A fast-path exists for iso8601-formatted dates.
    date_format : str or dict of column -> format, default ``None``
        If used in conjunction with ``parse_dates``, will parse dates according to this
        format. For anything more complex,
        please read in as ``object`` and then apply :func:`to_datetime` as-needed.

        .. versionadded:: 2.0.0

    thousands : str, default None
        Thousands separator for parsing string columns to numeric.  Note that
        this parameter is only necessary for columns stored as TEXT in Excel,
        any numeric columns will automatically be parsed, regardless of display
        format.
    decimal : str, default '.'
        Character to recognize as decimal point for parsing string columns to numeric.
        Note that this parameter is only necessary for columns stored as TEXT in Excel,
        any numeric columns will automatically be parsed, regardless of display
        format.(e.g. use ',' for European data).
    comment : str, default None
        Comments out remainder of line. Pass a character or characters to this
        argument to indicate comments in the input file. Any data between the
        comment string and the end of the current line is ignored.
    skipfooter : int, default 0
        Rows at the end to skip (0-indexed).
    storage_options : dict, optional
        Extra options that make sense for a particular storage connection, e.g.
        host, port, username, password, etc. For HTTP(S) URLs the key-value pairs
        are forwarded to ``urllib.request.Request`` as header options. For other
        URLs (e.g. starting with "s3://", and "gcs://") the key-value pairs are
        forwarded to ``fsspec.open``. Please see ``fsspec`` and ``urllib`` for more
        details, and for more examples on storage options refer `here
        <https://pandas.pydata.org/docs/user_guide/io.html?
        highlight=storage_options#reading-writing-remote-files>`_.

    dtype_backend : {'numpy_nullable', 'pyarrow'}
        Back-end data type applied to the resultant :class:`DataFrame`
        (still experimental). If not specified, the default behavior
        is to not use nullable data types. If specified, the behavior
        is as follows:

        * ``"numpy_nullable"``: returns nullable-dtype-backed :class:`DataFrame`
        * ``"pyarrow"``: returns pyarrow-backed nullable

        :class:`ArrowDtype` :class:`DataFrame`

        .. versionadded:: 2.0

    engine_kwargs : dict, optional
        Arbitrary keyword arguments passed to excel engine.

    Returns
    -------
    DataFrame or dict of DataFrames
        DataFrame from the passed in Excel file. See notes in sheet_name
        argument for more information on when a dict of DataFrames is returned.

    See Also
    --------
    DataFrame.to_excel : Write DataFrame to an Excel file.
    DataFrame.to_csv : Write DataFrame to a comma-separated values (csv) file.
    read_csv : Read a comma-separated values (csv) file into DataFrame.
    read_fwf : Read a table of fixed-width formatted lines into DataFrame.

    Notes
    -----
    For specific information on the methods used for each Excel engine, refer to the
    pandas
    :ref:`user guide <io.excel_reader>`

    Examples
    --------
    The file can be read using the file name as string or an open file object:

    >>> pd.read_excel("tmp.xlsx", index_col=0)  # doctest: +SKIP
           Name  Value
    0   string1      1
    1   string2      2
    2  #Comment      3

    >>> pd.read_excel(open("tmp.xlsx", "rb"), sheet_name="Sheet3")  # doctest: +SKIP
       Unnamed: 0      Name  Value
    0           0   string1      1
    1           1   string2      2
    2           2  #Comment      3

    Index and header can be specified via the `index_col` and `header` arguments

    >>> pd.read_excel("tmp.xlsx", index_col=None, header=None)  # doctest: +SKIP
         0         1      2
    0  NaN      Name  Value
    1  0.0   string1      1
    2  1.0   string2      2
    3  2.0  #Comment      3

    Column types are inferred but can be explicitly specified

    >>> pd.read_excel(
    ...     "tmp.xlsx", index_col=0, dtype={"Name": str, "Value": float}
    ... )  # doctest: +SKIP
           Name  Value
    0   string1    1.0
    1   string2    2.0
    2  #Comment    3.0

    True, False, and NA values, and thousands separators have defaults,
    but can be explicitly specified, too. Supply the values you would like
    as strings or lists of strings!

    >>> pd.read_excel(
    ...     "tmp.xlsx", index_col=0, na_values=["string1", "string2"]
    ... )  # doctest: +SKIP
           Name  Value
    0       NaN      1
    1       NaN      2
    2  #Comment      3

    Comment lines in the excel input file can be skipped using the
    ``comment`` kwarg.

    >>> pd.read_excel("tmp.xlsx", index_col=0, comment="#")  # doctest: +SKIP
          Name  Value
    0  string1    1.0
    1  string2    2.0
    2     None    NaN

In [32]:
df = pd.read_excel('partner_data.xlsx', sheet_name= 'partner_data1', header=0)
df

ImportError: `Import openpyxl` failed.  Use pip or conda to install the openpyxl package.

In [5]:
df = pd.read_excel('partner_data.xlsx', index_col='id')
df

ImportError: `Import openpyxl` failed.  Use pip or conda to install the openpyxl package.

In [31]:
df1 = pd.read_excel(r'C:\01.temp\Таблица 1.xlsx')
df1

   Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3
0         NaN      Товар       Цена    Ноутбук
1         NaN    Ноутбук      50000          2
2         NaN       Мышь       1500         10
3         NaN    Монитор      15000          3

In [32]:
# Считываем данные из файла

Для чтения файлов формата csv существует функция `pd.read_csv`

In [33]:
help(pd.read_csv)

Help on function read_csv in module pandas:

read_csv(
    filepath_or_buffer: FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str],
    *,
    sep: str | None | lib.NoDefault = <no_default>,
    delimiter: str | None | lib.NoDefault = None,
    header: int | Sequence[int] | None | Literal['infer'] = 'infer',
    names: Sequence[Hashable] | None | lib.NoDefault = <no_default>,
    index_col: IndexLabel | Literal[False] | None = None,
    usecols: UsecolsArgType = None,
    dtype: DtypeArg | None = None,
    engine: CSVEngine | None = None,
    converters: Mapping[HashableT, Callable] | None = None,
    true_values: list | None = None,
    false_values: list | None = None,
    skipinitialspace: bool = False,
    skiprows: list[int] | int | Callable[[Hashable], bool] | None = None,
    skipfooter: int = 0,
    nrows: int | None = None,
    na_values: Hashable | Iterable[Hashable] | Mapping[Hashable, Iterable[Hashable]] | None = None,
    keep_default_na: bool = True,
    na_filter: bool = True,
    skip_blank_lines: bool = True,
    parse_dates: bool | Sequence[Hashable] | None = None,
    date_format: str | dict[Hashable, str] | None = None,
    dayfirst: bool = False,
    cache_dates: bool = True,
    iterator: bool = False,
    chunksize: int | None = None,
    compression: CompressionOptions = 'infer',
    thousands: str | None = None,
    decimal: str = '.',
    lineterminator: str | None = None,
    quotechar: str = '"',
    quoting: int = 0,
    doublequote: bool = True,
    escapechar: str | None = None,
    comment: str | None = None,
    encoding: str | None = None,
    encoding_errors: str | None = 'strict',
    dialect: str | csv.Dialect | None = None,
    on_bad_lines: str = 'error',
    low_memory: bool = True,
    memory_map: bool = False,
    float_precision: Literal['high', 'legacy', 'round_trip'] | None = None,
    storage_options: StorageOptions | None = None,
    dtype_backend: DtypeBackend | lib.NoDefault = <no_default>
) -> DataFrame | TextFileReader
    Read a comma-separated values (csv) file into DataFrame.

    Also supports optionally iterating or breaking of the file
    into chunks.

    Additional help can be found in the online docs for
    `IO Tools <https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html>`_.

    Parameters
    ----------
    filepath_or_buffer : str, path object or file-like object
        Any valid string path is acceptable. The string could be a URL. Valid
        URL schemes include http, ftp, s3, gs, and file. For file URLs, a host is
        expected. A local file could be: file://localhost/path/to/table.csv.

        If you want to pass in a path object, pandas accepts any ``os.PathLike``.

        By file-like object, we refer to objects with a ``read()`` method, such as
        a file handle (e.g. via builtin ``open`` function) or ``StringIO``.
    sep : str, default ','
        Character or regex pattern to treat as the delimiter. If ``sep=None``, the
        C engine cannot automatically detect
        the separator, but the Python parsing engine can, meaning the latter will
        be used and automatically detect the separator from only the first valid
        row of the file by Python's builtin sniffer tool, ``csv.Sniffer``.
        In addition, separators longer than 1 character and different from
        ``'\s+'`` will be interpreted as regular expressions and will also force
        the use of the Python parsing engine. Note that regex delimiters are prone
        to ignoring quoted data. Regex example: ``'\r\t'``.
    delimiter : str, optional
        Alias for ``sep``.
    header : int, Sequence of int, 'infer' or None, default 'infer'
        Row number(s) containing column labels and marking the start of the
        data (zero-indexed). Default behavior is to infer the column names:
        if no ``names``
        are passed the behavior is identical to ``header=0`` and column
        names are inferred from the first line of the file, if column
        names are passed explicitly to ``names`` then the behavior is identical to
        ``header=None``. Explicitly pass ``header=0`` to be able to
        replace existing names. The header can be a list of integers that
        specify row locations for a :class:`~pandas.MultiIndex` on the columns
        e.g. ``[0, 1, 3]``. Intervening rows that are not specified will be
        skipped (e.g. 2 in this example is skipped). Note that this
        parameter ignores commented lines and empty lines if
        ``skip_blank_lines=True``, so ``header=0`` denotes the first line of
        data rather than the first line of the file.

        When inferred from the file contents, headers are kept distinct from
        each other by renaming duplicate names with a numeric suffix of the form
        ``".{count}"`` starting from 1, e.g. ``"foo"`` and ``"foo.1"``.
        Empty headers are named ``"Unnamed: {i}"`` or ``
        "Unnamed: {i}_level_{level}"``
        in the case of MultiIndex columns.
    names : Sequence of Hashable, optional
        Sequence of column labels to apply. If the file contains a header row,
        then you should explicitly pass ``header=0`` to override the column names.
        Duplicates in this list are not allowed.
    index_col : Hashable, Sequence of Hashable or False, optional
        Column(s) to use as row label(s), denoted either by column labels or column
        indices.  If a sequence of labels or indices is given,
        :class:`~pandas.MultiIndex`
        will be formed for the row labels.

        Note: ``index_col=False`` can be used to force pandas to *not* use the first
        column as the index, e.g., when you have a malformed file with delimiters at
        the end of each line.
    usecols : Sequence of Hashable or Callable, optional
        Subset of columns to select, denoted either
        by column labels or column indices.
        If list-like, all elements must either
        be positional (i.e. integer indices into the document columns) or strings
        that correspond to column names provided either by the user in ``names`` or
        inferred from the document header row(s).
        If ``names`` are given, the document
        header row(s) are not taken into account. For example, a valid list-like
        ``usecols`` parameter would be ``[0, 1, 2]`` or ``['foo', 'bar', 'baz']``.
        Element order is ignored, so ``usecols=[0, 1]`` is the same as ``[1, 0]``.
        To instantiate a :class:`~pandas.DataFrame` from ``data`` with element order
        preserved use ``pd.read_csv(data, usecols=['foo', 'bar'])[['foo', 'bar']]``
        for columns in ``['foo', 'bar']`` order or
        ``pd.read_csv(data, usecols=['foo', 'bar'])[['bar', 'foo']]``
        for ``['bar', 'foo']`` order.

        If callable, the callable function will be evaluated against the column
        names, returning names where the callable function evaluates to ``True``. An
        example of a valid callable argument would be ``lambda x: x.upper() in
        ['AAA', 'BBB', 'DDD']``. Using this parameter results in much faster
        parsing time and lower memory usage.
    dtype : dtype or dict of {Hashable : dtype}, optional
        Data type(s) to apply to either the whole dataset or individual columns.
        E.g., ``{'a': np.float64, 'b': np.int32, 'c': 'Int64'}``
        Use ``str`` or ``object`` together with suitable ``na_values`` settings
        to preserve and not interpret ``dtype``.
        If ``converters`` are specified, they will be applied INSTEAD
        of ``dtype`` conversion. Specify a ``defaultdict`` as input where
        the default determines the ``dtype``
        of the columns which are not explicitly
        listed.
    engine : {'c', 'python', 'pyarrow'}, optional
        Parser engine to use. The C and pyarrow engines are faster,
        while the python engine
        is currently more feature-complete. Multithreading
        is currently only supported by
        the pyarrow engine. Some features of the "pyarrow" engine
        are unsupported or may not work correctly.
    converters : dict of {Hashable : Callable}, optional
        Functions for converting values in specified columns. Keys can either
        be column labels or column indices.
    true_values : list, optional
        Values to consider as ``True`` in addition
        to case-insensitive variants of 'True'.
    false_values : list, optional
        Values to consider as ``False`` in addition to case-insensitive
        variants of 'False'.
    skipinitialspace : bool, default False
        Skip spaces after delimiter.
    skiprows : int, list of int or Callable, optional
        Line numbers to skip (0-indexed) or number of lines to skip (``int``)
        at the start of the file.

        If callable, the callable function will be evaluated against the row
        indices, returning ``True`` if the row should be skipped and ``False``
        otherwise.
        An example of a valid callable argument would be ``lambda x: x in [0, 2]``.
    skipfooter : int, default 0
        Number of lines at bottom of file to skip (Unsupported with ``engine='c'``).
    nrows : int, optional
        Number of rows of file to read. Useful for reading pieces of large files.
        Refers to the number of data rows in the returned DataFrame, excluding:

        * The header row containing column names.
        * Rows before the header row, if ``header=1`` or larger.

        Example usage:

        * To read the first 999,999 (non-header) rows:
          ``read_csv(..., nrows=999999)``

        * To read rows 1,000,000 through 1,999,999:
          ``read_csv(..., skiprows=1000000, nrows=999999)``

    na_values : Hashable, Iterable of Hashable or dict of {Hashable : Iterable},
        optional
        Additional strings to recognize as ``NA``/``NaN``. If ``dict``
        passed, specific
        per-column ``NA`` values.  By default the following values
        are interpreted as
        ``NaN``: empty string, "NaN", "N/A", "NULL", and other common
        representations of missing data.
    keep_default_na : bool, default True
        Whether or not to include the default ``NaN`` values when parsing the data.
        Depending on whether ``na_values`` is passed in, the behavior is as follows:

        * If ``keep_default_na`` is ``True``, and ``na_values``
          are specified, ``na_values``
          is appended to the default ``NaN`` values used for parsing.
        * If ``keep_default_na`` is ``True``, and ``na_values`` are not specified, only
          the default ``NaN`` values are used for parsing.
        * If ``keep_default_na`` is ``False``, and ``na_values`` are specified, only
          the ``NaN`` values specified ``na_values`` are used for parsing.
        * If ``keep_default_na`` is ``False``, and ``na_values`` are not specified, no
          strings will be parsed as ``NaN``.

        Note that if ``na_filter`` is passed in as ``False``,
        the ``keep_default_na`` and
        ``na_values`` parameters will be ignored.
    na_filter : bool, default True
        Detect missing value markers (empty strings and the value of ``na_values``). In
        data without any ``NA`` values, passing ``na_filter=False`` can improve the
        performance of reading a large file.
    skip_blank_lines : bool, default True
        If ``True``, skip over blank lines rather than interpreting as ``NaN`` values.
    parse_dates : bool, None, list of Hashable, default None
        The behavior is as follows:

        * ``bool``. If ``True`` -> try parsing the index.
        * ``None``. Behaves like ``True`` if ``date_format`` is specified.
        * ``list`` of ``int`` or names.
          e.g. If ``[1, 2, 3]`` -> try parsing columns 1, 2, 3
          each as a separate date column.

        If a column or index cannot be represented as an array of ``datetime``,
        say because of an unparsable value or a mixture of timezones, the column
        or index will be returned unaltered as an ``object`` data type. For
        non-standard ``datetime`` parsing, use :func:`~pandas.to_datetime` after
        :func:`~pandas.read_csv`.

        Note: A fast-path exists for iso8601-formatted dates.
    date_format : str or dict of column -> format, optional
        Format to use for parsing dates and/or times when
        used in conjunction with ``parse_dates``.
        The strftime to parse time, e.g. :const:`"%d/%m/%Y"`. See
        `strftime documentation
        <https://docs.python.org/3/library/datetime.html
        #strftime-and-strptime-behavior>`_ for more information on choices, though
        note that :const:`"%f"`` will parse all the way up to nanoseconds.
        You can also pass:

        - "ISO8601", to parse any `ISO8601 <https://en.wikipedia.org/wiki/ISO_8601>`_
          time string (not necessarily in exactly the same format);
        - "mixed", to infer the format for each element individually. This is risky,
          and you should probably use it along with `dayfirst`.

        .. versionadded:: 2.0.0
    dayfirst : bool, default False
        DD/MM format dates, international and European format.
    cache_dates : bool, default True
        If ``True``, use a cache of unique, converted dates to apply the ``datetime``
        conversion. May produce significant speed-up when parsing duplicate
        date strings, especially ones with timezone offsets.

    iterator : bool, default False
        Return ``TextFileReader`` object for iteration or getting chunks with
        ``get_chunk()``.
    chunksize : int, optional
        Number of lines to read from the file per chunk. Passing a value will cause the
        function to return a ``TextFileReader`` object for iteration.
        See the `IO Tools docs
        <https://pandas.pydata.org/pandas-docs/stable/io.html#io-chunking>`_
        for more information on ``iterator`` and ``chunksize``.

    compression : str or dict, default 'infer'
        For on-the-fly decompression of on-disk data.
        If 'infer' and 'filepath_or_buffer' is
        path-like, then detect compression from the following extensions: '.gz',
        '.bz2', '.zip', '.xz', '.zst', '.tar', '.tar.gz', '.tar.xz' or '.tar.bz2'
        (otherwise no compression).
        If using 'zip' or 'tar', the ZIP file must contain only
        one data file to be read in.
        Set to ``None`` for no decompression.
        Can also be a dict with key ``'method'`` set
        to one of {``'zip'``, ``'gzip'``, ``'bz2'``,
        ``'zstd'``, ``'xz'``, ``'tar'``} and
        other key-value pairs are forwarded to
        ``zipfile.ZipFile``, ``gzip.GzipFile``,
        ``bz2.BZ2File``, ``zstandard.ZstdDecompressor``, ``lzma.LZMAFile`` or
        ``tarfile.TarFile``, respectively.
        As an example, the following could be passed for
        Zstandard decompression using a
        custom compression dictionary:
        ``compression={'method': 'zstd', 'dict_data': my_compression_dict}``.

    thousands : str (length 1), optional
        Character acting as the thousands separator in numerical values.
    decimal : str (length 1), default '.'
        Character to recognize as decimal point (e.g., use ',' for European data).
    lineterminator : str (length 1), optional
        Character used to denote a line break. Only valid with C parser.
    quotechar : str (length 1), optional
        Character used to denote the start and end of a quoted item. Quoted
        items can include the ``delimiter`` and it will be ignored.
    quoting : {0 or csv.QUOTE_MINIMAL, 1 or csv.QUOTE_ALL,
        2 or csv.QUOTE_NONNUMERIC, 3 or csv.QUOTE_NONE}, default csv.QUOTE_MINIMAL
        Control field quoting behavior per ``csv.QUOTE_*`` constants. Default is
        ``csv.QUOTE_MINIMAL`` (i.e., 0) which implies that
        only fields containing special
        characters are quoted (e.g., characters defined
        in ``quotechar``, ``delimiter``,
        or ``lineterminator``.
    doublequote : bool, default True
        When ``quotechar`` is specified and ``quoting`` is not ``QUOTE_NONE``, indicate
        whether or not to interpret two consecutive ``quotechar`` elements INSIDE a
        field as a single ``quotechar`` element.
    escapechar : str (length 1), optional
        Character used to escape other characters.
    comment : str (length 1), optional
        Character indicating that the remainder of line should not be parsed.
        If found at the beginning
        of a line, the line will be ignored altogether. This parameter must be a
        single character. Like empty lines (as long as ``skip_blank_lines=True``),
        fully commented lines are ignored by the parameter ``header`` but not by
        ``skiprows``. For example, if ``comment='#'``, parsing
        ``#empty\na,b,c\n1,2,3`` with ``header=0`` will result in ``'a,b,c'`` being
        treated as the header.
    encoding : str, optional, default 'utf-8'
        Encoding to use for UTF when reading/writing (ex. ``'utf-8'``). `List of Python
        standard encodings
        <https://docs.python.org/3/library/codecs.html#standard-encodings>`_ .

    encoding_errors : str, optional, default 'strict'
        How encoding errors are treated. `List of possible values
        <https://docs.python.org/3/library/codecs.html#error-handlers>`_ .

    dialect : str or csv.Dialect, optional
        If provided, this parameter will override values (default or not) for the
        following parameters: ``delimiter``, ``doublequote``, ``escapechar``,
        ``skipinitialspace``, ``quotechar``, and ``quoting``. If it is necessary to
        override values, a ``ParserWarning`` will be issued. See ``csv.Dialect``
        documentation for more details.
    on_bad_lines : {'error', 'warn', 'skip'} or Callable, default 'error'
        Specifies what to do upon encountering a bad line (a line with too many fields).
        Allowed values are:

        - ``'error'``, raise an Exception when a bad line is encountered.
        - ``'warn'``, raise a warning when a bad line is
          encountered and skip that line.
        - ``'skip'``, skip bad lines without raising or warning when
          they are encountered.
        - Callable, function that will process a single bad line.
            - With ``engine='python'``, function with signature
              ``(bad_line: list[str]) -> list[str] | None``.
              ``bad_line`` is a list of strings split by the ``sep``.
              If the function returns ``None``, the bad line will be ignored.
              If the function returns a new ``list`` of strings with
              more elements than
              expected, a ``ParserWarning`` will be emitted while
              dropping extra elements.
            - With ``engine='pyarrow'``, function with signature
              as described in pyarrow documentation: `invalid_row_handler
              <https://arrow.apache.org/docs/python
              /generated/pyarrow.csv.ParseOptions.html
              #pyarrow.csv.ParseOptions.invalid_row_handler>`_.

        .. versionchanged:: 2.2.0

            Callable for ``engine='pyarrow'``

    low_memory : bool, default True
        Internally process the file in chunks, resulting in lower memory use
        while parsing, but possibly mixed type inference.  To ensure no mixed
        types either set ``False``, or specify the type with the ``dtype`` parameter.
        Note that the entire file is read into a single :class:`~pandas.DataFrame`
        regardless, use the ``chunksize`` or ``iterator``
        parameter to return the data in
        chunks. (Only valid with C parser).
    memory_map : bool, default False
        If a filepath is provided for ``filepath_or_buffer``, map the file object
        directly onto memory and access the data directly from there. Using this
        option can improve performance because there is no longer any I/O overhead.

In [8]:
pd.read_csv('partner_data.csv')

,id,age,job,marital,education,balance,housing,loan,default
0,1,26.0,unemployed,married,tertiary,454,yes,yes,no
1,2,25.0,technician,married,secondary,517,no,no,no
2,3,36.0,technician,single,secondary,1044,yes,no,no
3,4,45.0,blue-collar,married,secondary,146,yes,yes,no
4,5,27.0,management,married,tertiary,145,no,no,no
...,...,...,...,...,...,...,...,...,...
995,996,41.0,entrepreneur,married,secondary,-1882,yes,no,no
996,997,58.0,management,married,tertiary,1271,yes,no,no
997,998,31.0,services,single,secondary,297,no,no,no
998,999,31.0,entrepreneur,NaN,tertiary,312,no,no,no
999,1000,23.0,blue-collar,single,secondary,780,yes,no,no

In [35]:
pd.read_csv('partner_data_semicolon.csv')

    id;age;job;marital;education;balance;housing;loan;default
0    1;26.0;unemployed;married;tertiary;454;yes;yes;no
1     2;25.0;technician;married;secondary;517;no;no;no
2    3;36.0;technician;single;secondary;1044;yes;no;no
3    4;45.0;blue-collar;married;secondary;146;yes;y...
4      5;27.0;management;married;tertiary;145;no;no;no
..                                                 ...
995  996;41.0;entrepreneur;married;secondary;-1882;...
996  997;58.0;management;married;tertiary;1271;yes;...
997    998;31.0;services;single;secondary;297;no;no;no
998       999;31.0;entrepreneur;;tertiary;312;no;no;no
999  1000;23.0;blue-collar;single;secondary;780;yes...

[1000 rows x 1 columns]

In [9]:
pd.read_csv('partner_data_semicolon.csv', sep= ';')

,id,age,job,marital,education,balance,housing,loan,default
0,1,26.0,unemployed,married,tertiary,454,yes,yes,no
1,2,25.0,technician,married,secondary,517,no,no,no
2,3,36.0,technician,single,secondary,1044,yes,no,no
3,4,45.0,blue-collar,married,secondary,146,yes,yes,no
4,5,27.0,management,married,tertiary,145,no,no,no
...,...,...,...,...,...,...,...,...,...
995,996,41.0,entrepreneur,married,secondary,-1882,yes,no,no
996,997,58.0,management,married,tertiary,1271,yes,no,no
997,998,31.0,services,single,secondary,297,no,no,no
998,999,31.0,entrepreneur,NaN,tertiary,312,no,no,no
999,1000,23.0,blue-collar,single,secondary,780,yes,no,no

In [40]:
pd.read_csv('partner_data_semicolon.csv', delimiter= ';')

,id,age,job,marital,education,balance,housing,loan,default
0,1,26.0,unemployed,married,tertiary,454,yes,yes,no
1,2,25.0,technician,married,secondary,517,no,no,no
2,3,36.0,technician,single,secondary,1044,yes,no,no
3,4,45.0,blue-collar,married,secondary,146,yes,yes,no
4,5,27.0,management,married,tertiary,145,no,no,no
...,...,...,...,...,...,...,...,...,...
995,996,41.0,entrepreneur,married,secondary,-1882,yes,no,no
996,997,58.0,management,married,tertiary,1271,yes,no,no
997,998,31.0,services,single,secondary,297,no,no,no
998,999,31.0,entrepreneur,NaN,tertiary,312,no,no,no
999,1000,23.0,blue-collar,single,secondary,780,yes,no,no

## Получение общего представления о данных

### head(), tail()

In [41]:
# Вывод первых 5 строк(по умолчанию), количество можно указать
df.head()

   id   age          job  marital  education  balance housing loan default
0   1  26.0   unemployed  married   tertiary      454     yes  yes      no
1   2  25.0   technician  married  secondary      517      no   no      no
2   3  36.0   technician   single  secondary     1044     yes   no      no
3   4  45.0  blue-collar  married  secondary      146     yes  yes      no
4   5  27.0   management  married   tertiary      145      no   no      no

In [42]:
# Вывод последних 5 строк(по умолчанию), количество можно указать
df.head(2)

   id   age         job  marital  education  balance housing loan default
0   1  26.0  unemployed  married   tertiary      454     yes  yes      no
1   2  25.0  technician  married  secondary      517      no   no      no

### info(), describe(), shape, dtypes, columns

In [43]:
# Получение общей информации о датасетева
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         1000 non-null   int64
 1   age        901 non-null    float64
 2   job        1000 non-null   str
 3   marital    897 non-null    str
 4   education  1000 non-null   str
 5   balance    1000 non-null   int64
 6   housing    1000 non-null   str
 7   loan       1000 non-null   str
 8   default    1000 non-null   str
dtypes: float64(1), int64(2), str(6)
memory usage: 70.4 KB

In [44]:
# Получение статистической информации о датасете, по умолчанию для числовых колонок
df.describe()

                id         age       balance
count  1000.000000  901.000000   1000.000000
mean    500.500000   40.819090   1334.894000
std     288.819436   11.220097   2746.106944
min       1.000000   18.000000  -3372.000000
25%     250.750000   32.000000     67.750000
50%     500.500000   39.000000    484.000000
75%     750.250000   48.000000   1495.250000
max    1000.000000   88.000000  36221.000000

In [45]:
# Размерность датасета
df.shape

(1000, 9)

In [46]:
# Типы данных
df.dtypes

id             int64
age          float64
job              str
marital          str
education        str
balance        int64
housing          str
loan             str
default          str
dtype: object

In [47]:
# Названия столбцов
df.columns

Index(['id', 'age', 'job', 'marital', 'education', 'balance', 'housing',
       'loan', 'default'],
      dtype='str')

# <a id="loc_iloc">3. Методы loc и iloc для доступа к данным датасета</a>

Для обращения к элементам таблицы — строкам и столбцам — существует два основных метода:
* `.iloc — выбор элементов по индексу`
* `.loc — выбор элементов по названию`

### Работа с Series
Чтобы создать series в pandas необходимо использовать следующий синтаксис \
`pd.Series(data, index, name='A name')`

In [48]:
age_series = pd.Series(df['age'], name = 'Возраст')
age_series

0      26.0
1      25.0
2      36.0
3      45.0
4      27.0
       ...
995    41.0
996    58.0
997    31.0
998    31.0
999    23.0
Name: Возраст, Length: 1000, dtype: float64

In [49]:
age_series_2 = df['age']
age_series_2

0      26.0
1      25.0
2      36.0
3      45.0
4      27.0
       ...
995    41.0
996    58.0
997    31.0
998    31.0
999    23.0
Name: age, Length: 1000, dtype: float64

In [47]:
df.age

id
1       26.0
2       25.0
3       36.0
4       45.0
5       27.0
        ...
996     41.0
997     58.0
998     31.0
999     31.0
1000    23.0
Name: age, Length: 1000, dtype: float64

In [48]:
age_series.iloc[0]

np.float64(26.0)

In [49]:
age_series.iloc[-1]

np.float64(23.0)

In [50]:
age_series.iloc[0:10]

0    26.0
1    25.0
2    36.0
3    45.0
4    27.0
5    45.0
6    35.0
7    27.0
8     NaN
9    32.0
Name: Возраст, dtype: float64

In [51]:
age_series.iloc[:-2]

0      26.0
1      25.0
2      36.0
3      45.0
4      27.0
       ...
993    37.0
994     NaN
995    41.0
996    58.0
997    31.0
Name: Возраст, Length: 998, dtype: float64

### Работа с Dataframe

In [52]:
df.iloc[0,0]

np.int64(1)

In [53]:
df.iloc[0:3, 0]

0    1
1    2
2    3
Name: id, dtype: int64

In [54]:
df.iloc[: , 0]

0         1
1         2
2         3
3         4
4         5
       ...
995     996
996     997
997     998
998     999
999    1000
Name: id, Length: 1000, dtype: int64

In [55]:
df.iloc[4:5, 2:4]

          job  marital
4  management  married

In [56]:
df.loc[1, 'age']

np.float64(25.0)

In [57]:
df.loc[2, 'age']

np.float64(36.0)

In [58]:
df.loc[1:3, 'age']

1    25.0
2    36.0
3    45.0
Name: age, dtype: float64

In [60]:
df.loc[: , 'age']

id
1       26.0
2       25.0
3       36.0
4       45.0
5       27.0
        ...
996     41.0
997     58.0
998     31.0
999     31.0
1000    23.0
Name: age, Length: 1000, dtype: float64

In [61]:
df.loc[1 , :]

age                26.0
job          unemployed
marital         married
education      tertiary
balance             454
housing             yes
loan                yes
default              no
Name: 1, dtype: object

In [62]:
df.loc[5:6,'balance':'loan']

    balance housing loan
id
5       145      no   no
6        11      no   no

In [63]:
df[['age','marital','loan']]

       age  marital loan
id
1     26.0  married  yes
2     25.0  married   no
3     36.0   single   no
4     45.0  married  yes
5     27.0  married   no
...    ...      ...  ...
996   41.0  married   no
997   58.0  married   no
998   31.0   single   no
999   31.0      NaN   no
1000  23.0   single   no

[1000 rows x 3 columns]

# <a id="filter">4. Фильтрация данных по условию</a>

### Простые условия

In [59]:
# Формируем условие для фильтра, выведем клиентов старше 30
age_series > 30

0      False
1      False
2       True
3       True
4      False
       ...
995     True
996     True
997     True
998     True
999    False
Name: Возраст, Length: 1000, dtype: bool

In [60]:
age_series[age_series > 30]

2      36.0
3      45.0
5      45.0
6      35.0
9      32.0
       ...
993    37.0
995    41.0
996    58.0
997    31.0
998    31.0
Name: Возраст, Length: 741, dtype: float64

In [61]:
df['age'] > 30

0      False
1      False
2       True
3       True
4      False
       ...
995     True
996     True
997     True
998     True
999    False
Name: age, Length: 1000, dtype: bool

In [62]:
df[df['age'] > 30]

,id,age,job,marital,education,balance,housing,loan,default
2,3,36.0,technician,single,secondary,1044,yes,no,no
3,4,45.0,blue-collar,married,secondary,146,yes,yes,no
5,6,45.0,unemployed,divorced,primary,11,no,no,yes
6,7,35.0,management,married,tertiary,298,yes,no,no
9,10,32.0,unemployed,married,secondary,10,yes,no,no
...,...,...,...,...,...,...,...,...,...
993,994,37.0,management,divorced,tertiary,241,yes,no,no
995,996,41.0,entrepreneur,married,secondary,-1882,yes,no,no
996,997,58.0,management,married,tertiary,1271,yes,no,no
997,998,31.0,services,single,secondary,297,no,no,no
998,999,31.0,entrepreneur,NaN,tertiary,312,no,no,no

In [63]:
df[df['age'] > 30]['marital']

2        single
3       married
5      divorced
6       married
9       married
         ...
993    divorced
995     married
996     married
997      single
998         NaN
Name: marital, Length: 741, dtype: str

In [64]:
df[df['age'] > 30][['marital','balance']]

      marital  balance
2      single     1044
3     married      146
5    divorced       11
6     married      298
9     married       10
..        ...      ...
993  divorced      241
995   married    -1882
996   married     1271
997    single      297
998       NaN      312

[741 rows x 2 columns]

### Сложные условия

In [ ]:
df.marital.unique()

<StringArray>
['married', 'single', 'divorced', nan]
Length: 4, dtype: str

In [ ]:
# Вывести на экран клиентов, у которых статус job 'unemployed' и статус marital 'marrige'
(df['job'] == 'unemployed') & (df['marital'] == 'married')

0       True
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [67]:
df[(df['job'] == 'unemployed') & (df['marital'] == 'married')]

      id   age         job  marital  education  balance housing loan default
0      1  26.0  unemployed  married   tertiary      454     yes  yes      no
9     10  32.0  unemployed  married  secondary       10     yes   no      no
123  124  35.0  unemployed  married  secondary      978      no   no      no
132  133  52.0  unemployed  married   tertiary     1595      no   no      no
203  204   NaN  unemployed  married  secondary     1466     yes   no     yes
223  224  43.0  unemployed  married    primary      960     yes  yes      no
322  323  53.0  unemployed  married  secondary     -233     yes   no     yes
365  366  39.0  unemployed  married   tertiary     1108     yes   no      no
374  375   NaN  unemployed  married  secondary    36221      no   no      no
468  469  32.0  unemployed  married  secondary        2     yes   no     yes
496  497  48.0  unemployed  married    primary        0      no   no      no
505  506  57.0  unemployed  married  secondary     1681      no   no      no
580  581   NaN  unemployed  married    primary      168     yes   no      no
637  638  29.0  unemployed  married   tertiary        8     yes   no      no
646  647  28.0  unemployed  married  secondary      863     yes  yes      no
693  694   NaN  unemployed  married  secondary      277     yes   no      no
744  745  35.0  unemployed  married    primary      494     yes   no      no
806  807   NaN  unemployed  married  secondary     2629      no   no      no
849  850  33.0  unemployed  married  secondary      456      no   no      no
960  961  49.0  unemployed  married  secondary     4110      no   no      no
977  978  51.0  unemployed  married  secondary    17418     yes   no     yes

In [68]:
# Ввывести на экран клиентов старше 40 и размер накоплений более 1000

df[(df['age'] > 40) & (df['balance'] > 1000)]

      id   age          job  marital  education  balance housing loan default
17    18  47.0  blue-collar      NaN  secondary     3630     yes   no      no
19    20  47.0  blue-collar  married    primary     1452     yes  yes      no
28    29  57.0  blue-collar      NaN    primary     3109      no   no      no
30    31  44.0     services  married  secondary     3536      no   no      no
43    44  53.0  blue-collar  married  secondary     1777     yes   no      no
..   ...   ...          ...      ...        ...      ...     ...  ...     ...
967  968  57.0      retired  married    primary     9367      no   no      no
977  978  51.0   unemployed  married  secondary    17418     yes   no     yes
981  982  46.0       admin.  married  secondary     3028     yes  yes      no
991  992  48.0      unknown   single    unknown     1819      no   no      no
996  997  58.0   management  married   tertiary     1271     yes   no      no

[150 rows x 9 columns]

In [74]:
df

       age           job  marital  education  balance housing loan default
id
1     26.0    unemployed  married   tertiary      454     yes  yes      no
2     25.0    technician  married  secondary      517      no   no      no
3     36.0    technician   single  secondary     1044     yes   no      no
4     45.0   blue-collar  married  secondary      146     yes  yes      no
5     27.0    management  married   tertiary      145      no   no      no
...    ...           ...      ...        ...      ...     ...  ...     ...
996   41.0  entrepreneur  married  secondary    -1882     yes   no      no
997   58.0    management  married   tertiary     1271     yes   no      no
998   31.0      services   single  secondary      297      no   no      no
999   31.0  entrepreneur      NaN   tertiary      312      no   no      no
1000  23.0   blue-collar   single  secondary      780     yes   no      no

[1000 rows x 8 columns]

In [74]:
df = df.reset_index()
df

ValueError: cannot insert level_0, already exists

## Полезные функции для фильтрации данных

### isin()

In [75]:
df

,level_0,index,id,age,job,marital,education,balance,housing,loan,default
0,0,0,1,26.0,unemployed,married,tertiary,454,yes,yes,no
1,1,1,2,25.0,technician,married,secondary,517,no,no,no
2,2,2,3,36.0,technician,single,secondary,1044,yes,no,no
3,3,3,4,45.0,blue-collar,married,secondary,146,yes,yes,no
4,4,4,5,27.0,management,married,tertiary,145,no,no,no
...,...,...,...,...,...,...,...,...,...,...,...
995,995,995,996,41.0,entrepreneur,married,secondary,-1882,yes,no,no
996,996,996,997,58.0,management,married,tertiary,1271,yes,no,no
997,997,997,998,31.0,services,single,secondary,297,no,no,no
998,998,998,999,31.0,entrepreneur,NaN,tertiary,312,no,no,no
999,999,999,1000,23.0,blue-collar,single,secondary,780,yes,no,no

### isnull() / notnull(), any(), all()

In [76]:
# Показать, есть ли пропуски в каждом столбце
df.isnull().any()

level_0      False
index        False
id           False
age           True
job          False
marital       True
education    False
balance      False
housing      False
loan         False
default      False
dtype: bool

In [77]:
# Показать, есть ли пропуски в каждой строке

In [78]:
# Показать, полностью ли столбец состоит из пропусков

In [79]:
# Показать, есть ли пропуски в каждой строке

In [80]:
# Вывести все пустые строки таблицы

In [77]:
# Вывести все заполненные строки таблицы
df.dropna(axis = 0, how = 'all')

,level_0,index,id,age,job,marital,education,balance,housing,loan,default
0,0,0,1,26.0,unemployed,married,tertiary,454,yes,yes,no
1,1,1,2,25.0,technician,married,secondary,517,no,no,no
2,2,2,3,36.0,technician,single,secondary,1044,yes,no,no
3,3,3,4,45.0,blue-collar,married,secondary,146,yes,yes,no
4,4,4,5,27.0,management,married,tertiary,145,no,no,no
...,...,...,...,...,...,...,...,...,...,...,...
995,995,995,996,41.0,entrepreneur,married,secondary,-1882,yes,no,no
996,996,996,997,58.0,management,married,tertiary,1271,yes,no,no
997,997,997,998,31.0,services,single,secondary,297,no,no,no
998,998,998,999,31.0,entrepreneur,NaN,tertiary,312,no,no,no
999,999,999,1000,23.0,blue-collar,single,secondary,780,yes,no,no

# <a id="output">5. Сохранение в файл</a>

In [78]:
# Сохранить в файле notnull.xlsx те записи, которые не содержат пропусков

# df_notnull = df.dropna()
df_notnull = df[df.notnull().all(axis = 1)]
df_notnull.to_excel('notnull.xlsx', index = False)

ModuleNotFoundError: No module named 'openpyxl'

# <a id="agregat">6. Применение агрегирующих функций</a>

## Агрегирующие функции

- max() -	максимум
- min()	- минимум
- mean() - среднее значение
- sum()	- сумма
- count() -	количество непустых элементов
- std()	- стандартное отклонение

In [83]:
# Средний возраст наших клиентов

In [80]:
df_notnull[['age','balance']].mean()

age          40.545342
balance    1298.956522
dtype: float64

In [81]:
# Средний возраст и средняя сумма баланса наших клиентов
age_mean, balance_me = df_notnull[['age','balance']].mean()
print(f'Средний возраст:{age_mean:.2f}')

Средний возраст:40.55

In [86]:
# Минимальный  и максимальный возраст клиента в датасете
print(df_notnull.age.min())
print(df_notnull.age.max())

18.0
88.0

In [87]:
# Минимальный  и максимальный баланс клиента в датасете
print(df_notnull.balance.min())
print(df_notnull.balance.max())

-3372
31472

In [93]:
# Вывести на экран информацию о самом молодом
min_age = df_notnull.age.min()
df_notnull.age[df_notnull.age == min_age]

276    18.0
Name: age, dtype: float64

In [ ]:
df_notnull.age.idxmax()

In [95]:
df_notnull.age.idxmax()

np.int64(399)

In [94]:
# Вывести на экран информацию о самом возрастном
max_age = df_notnull.age.max()
df_notnull.age[df_notnull.age == max_age]

399    88.0
Name: age, dtype: float64

## <a id="groupby">7. Группировка данных</a>

### value_counts()

подсчитывает количество раз, которое значение встречается в колонке.

In [96]:
# Вывод количества значений столбцов
df_notnull.age.value_counts()

age
32.0    38
31.0    38
35.0    34
36.0    33
37.0    31
30.0    29
39.0    29
33.0    29
40.0    28
27.0    27
43.0    25
28.0    25
41.0    24
34.0    24
46.0    23
29.0    23
38.0    23
45.0    22
42.0    18
48.0    18
53.0    17
51.0    17
44.0    16
55.0    15
54.0    15
60.0    15
57.0    15
26.0    14
49.0    14
47.0    13
50.0    13
25.0    12
59.0    12
52.0    12
58.0    10
56.0    10
24.0     8
23.0     5
22.0     3
72.0     3
77.0     2
73.0     2
63.0     2
20.0     2
64.0     2
71.0     2
61.0     2
86.0     2
75.0     1
83.0     1
69.0     1
18.0     1
88.0     1
65.0     1
70.0     1
76.0     1
21.0     1
Name: count, dtype: int64

In [97]:
df_notnull.education.value_counts()

education
secondary    412
tertiary     247
primary      100
unknown       46
Name: count, dtype: int64

In [101]:
# Вывод количества значений в долях normalize=True
df_notnull.education.value_counts(normalize = True) * 100

education
secondary    51.180124
tertiary     30.683230
primary      12.422360
unknown       5.714286
Name: proportion, dtype: float64

In [100]:
# Вывод количества значений в %
df_notnull.education.value_counts()/len(df_notnull) * 100

education
secondary    51.180124
tertiary     30.683230
primary      12.422360
unknown       5.714286
Name: count, dtype: float64

In [104]:
df_notnull.balance/100

0       4.54
1       5.17
2      10.44
3       1.46
4       1.45
       ...
993     2.41
995   -18.82
996    12.71
997     2.97
999     7.80
Name: balance, Length: 805, dtype: float64

### groupby()
Группировка по одному или нескольким атрибутам.

In [105]:
df_notnull.groupby('marital')['balance'].mean()

marital
divorced     743.416667
married     1384.247166
single      1357.608209
Name: balance, dtype: float64

In [106]:
df_notnull.groupby('marital')[['balance', 'age']].mean()

              balance        age
marital
divorced   743.416667  46.677083
married   1384.247166  43.380952
single    1357.608209  33.682836

In [107]:
df_notnull.groupby(['marital','job'])[['balance', 'age']].mean()

                            balance        age
marital  job
divorced admin.          559.400000  42.400000
         blue-collar    1224.400000  44.500000
         entrepreneur   1456.000000  50.000000
         housemaid      1058.400000  43.200000
         management      267.850000  44.400000
         retired         812.222222  64.555556
         self-employed   457.333333  49.666667
         services        383.600000  47.400000
         technician      989.260870  44.565217
         unemployed     1174.500000  44.750000
married  admin.         1239.795918  38.897959
         blue-collar    1012.718750  41.960938
         entrepreneur    770.000000  44.266667
         housemaid       668.416667  45.083333
         management     1919.174419  44.593023
         retired        2246.370370  63.925926
         self-employed  1149.210526  44.000000
         services        977.575758  38.848485
         technician     1621.500000  41.571429
         unemployed     1869.000000  40.125000
single   admin.         1014.636364  33.272727
         blue-collar     747.333333  33.711111
         entrepreneur   1033.181818  34.545455
         housemaid      2268.500000  47.500000
         management     2073.253968  33.698413
         retired        1174.000000  63.500000
         self-employed  1345.285714  29.285714
         services       1215.730769  32.653846
         student        1696.529412  26.176471
         technician     1191.423077  34.634615
         unemployed     1360.333333  35.166667
         unknown        1670.500000  40.500000

In [110]:
df_notnull.groupby(['job', 'marital', 'education'])[['balance', 'age']].mean()

                                   balance        age
job        marital  education
admin.     divorced secondary   629.500000  41.000000
                    tertiary    279.000000  48.000000
           married  primary      31.000000  47.000000
                    secondary  1118.454545  38.636364
                    tertiary   5035.000000  37.000000
...                                    ...        ...
unemployed single   secondary   214.000000  34.333333
                    tertiary   3726.500000  39.500000
                    unknown      67.000000  29.000000
unknown    single   secondary  1522.000000  33.000000
                    unknown    1819.000000  48.000000

[93 rows x 2 columns]

In [112]:
df_notnull.groupby(['job', 'marital', 'education'], as_index=False)[['balance', 'age']].count()

           job   marital  education  balance  age
0       admin.  divorced  secondary        8    8
1       admin.  divorced   tertiary        2    2
2       admin.   married    primary        1    1
3       admin.   married  secondary       44   44
4       admin.   married   tertiary        2    2
..         ...       ...        ...      ...  ...
88  unemployed    single  secondary        3    3
89  unemployed    single   tertiary        2    2
90  unemployed    single    unknown        1    1
91     unknown    single  secondary        1    1
92     unknown    single    unknown        1    1

[93 rows x 5 columns]

In [113]:
df_notnull.groupby(['education'], as_index=False)[['balance', 'age']].count()

   education  balance  age
0    primary      100  100
1  secondary      412  412
2   tertiary      247  247
3    unknown       46   46

In [114]:
df_notnull.groupby(['marital'], as_index=False)[['balance', 'age']].count()

    marital  balance  age
0  divorced       96   96
1   married      441  441
2    single      268  268