# Итоговая работа по курсу

**Цели домашнего задания:**
- Закрепить на практике, изученные темы: использование циклов, работа со списками, написание функций, работа с текстом и работа в pandas

Для каждой задачи:
- программа выполняет все требуемые действия;
- результаты вычислений и операций корректны;
- вывод производится в том виде, который описан в задаче;
- переменные названы информативно.

### Как отправить работу на проверку
Выполните задачи, сохраните изменения при помощи вкладки меню File - Save as. Итоговый файл Jupyter Notebook .ipynb направьте на проверку на почту DigitalFaculty@digtp.com

# Управляющие конструкции. Циклы for и while

Задача 1. Напишите цикл, который выводит на печать все високосные годы начиная с 2020 года, но не позже 2050 года.

In [11]:
# Ваш код - Решение 1м способом
for year in range(2020, 2051, 4):
    print(f"{year} год — високосный.")

2020 год — високосный.
2024 год — високосный.
2028 год — високосный.
2032 год — високосный.
2036 год — високосный.
2040 год — високосный.
2044 год — високосный.
2048 год — високосный.

In [13]:
# Ваш код - Решение 2м способом
for year2 in range(2020, 2051):
    if year2 % 4 == 0:
        print(f"{year2} год - високосный.")

2020 год - високосный.
2024 год - високосный.
2028 год - високосный.
2032 год - високосный.
2036 год - високосный.
2040 год - високосный.
2044 год - високосный.
2048 год - високосный.

Задача 2. Напишите программу, которая бесконечно запрашивает на ввод целое число и после каждого ввода печатает на экране ответ в соответствии со следующими условиями:
  * Если введённое число делится на три, то печатается это же число.
  * Если делится на пять, то на печать выводится его квадрат. Если же это число одновременно делится и на пять, и на три, то на экране должно появиться само число в соответствии с прошлым условием, а затем и его квадрат. То есть сначала должно отработать прошлое условие, а затем текущее. 
  * Если число делится на семь, нужно вывести на печать «дурак совсем» и прервать выполнение программы. 
  * Во всех остальных случаях программа должна снова запросить число на ввод.

`Подсказка`

Чтобы проверить, что программа работает верно, можно использовать следующие числа для теста: 
* 3 (в ответ печатается 3);
* 5 (в ответ печатается 25);
* 15 (в ответ печатается 15 и 225);
* 1 (ничего не печатается, запрашивается следующее число на ввод);
* 7 (в ответ печатается «дурак совсем», программа прерывается).

In [16]:
# Ваш код
while True:
    num = int(input("Введите целое число: "))
    
    
    # проверка на условие, при котором завершается задание
    if num % 7 == 0:
        print("дурак совсем")
        break
        
    # проверка остальных условий по заданию
    if num % 3 == 0 and num % 5 == 0:
        print(f"{num} делится на 3 и на 5, его квадрат = {num ** 2}")
    elif num % 3 == 0:
        print(f"{num} делится на 3")
    elif num % 5 == 0:
        print(f"{num} делится на 5 и его квадрат {num ** 2}")

5 делится на 5 и его квадрат 25
3 делится на 3
15 делится на 3 и на 5, его квадрат = 225
25 делится на 5 и его квадрат 625
дурак совсем

# Списки

Задача 3. Дан список `list1`, который содержит целые числа. Всего в списке 12 элементов. 

- Ваша задача — посчитать сумму элементов с нечётными индексами. Другими словами, нужно сложить элементы `list1[1]`, `list1[3]`, `list1[5]`, `list1[7]`, `list1[9]` и `list1[11]`. 

- Чтобы решить эту задачу, используйте slicing. 

`Подсказка`: вам придётся указать одну границу среза и шаг.

In [17]:
list1 = [1, 3, 0, -2, 4, 5, 9, 12, -9, 16, -75, 8]

# Ваш код здесь
# 1. Делаем срез элементов с нечётными индексами
slice1 = list1[1::2]

# 2. Считаем сумму элементов в полученном срезе
result_sum = sum(slice1)

# Выводим результаты для проверки
print("Элементы с нечётными индексами:", slice1)
print("Их сумма:", result_sum)

Элементы с нечётными индексами: [3, -2, 5, 12, 16, 8]
Их сумма: 42

# Нормализация строк и функции

Задача 4. Очищение строк

Данные по фамилии и имени каждого пользователя приходят в виде строки вида: `Фамилия:Иванов,Имя:Герасим`. Напишите функцию, которая будет обрабатывать такую строку в качестве входного параметра, а на выходе будет возвращать два значения: фамилию и имя в нижнем регистре.

Проверьте, что ячейки ниже отработали верно.

In [18]:
def get_name_data(input_data: str):
    # Ваш код здесь
     # Разделяем строку на две части по запятой
    last_part, first_part = input_data.split(",")
    # Убираем подстроку 'Фамилия:', очищаем от пробелов по краям и переводим в нижний регистр
    last_name = last_part.replace("Фамилия:", "").strip().lower()
    
    # Убираем подстроку 'Имя:', очищаем от пробелов по краям и переводим в нижний регистр
    first_name = first_part.replace("Имя:", "").strip().lower()
    
    # Возвращаем кортеж из двух значений
    return last_name, first_name

In [19]:
get_name_data('Фамилия:Удовенко,Имя:Максим')

('удовенко', 'максим')

In [20]:
get_name_data('Фамилия:Сидоров-Ильин,Имя:Петр')

('сидоров-ильин', 'петр')

# Основы pandas

In [21]:
# Подключите библиотеку
import pandas as pd

In [22]:
# Считываем данные из файла athlete_events.csv
df = pd.read_csv('athlete_events.csv')

In [23]:
# Вывести первые 10 строк
df.head(10)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN
5,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,"Speed Skating Women's 1,000 metres",NaN
6,5,Christine Jacoba Aaftink,F,25.0,185.0,82.0,Netherlands,NED,1992 Winter,1992,Winter,Albertville,Speed Skating,Speed Skating Women's 500 metres,NaN
7,5,Christine Jacoba Aaftink,F,25.0,185.0,82.0,Netherlands,NED,1992 Winter,1992,Winter,Albertville,Speed Skating,"Speed Skating Women's 1,000 metres",NaN
8,5,Christine Jacoba Aaftink,F,27.0,185.0,82.0,Netherlands,NED,1994 Winter,1994,Winter,Lillehammer,Speed Skating,Speed Skating Women's 500 metres,NaN
9,5,Christine Jacoba Aaftink,F,27.0,185.0,82.0,Netherlands,NED,1994 Winter,1994,Winter,Lillehammer,Speed Skating,"Speed Skating Women's 1,000 metres",NaN

In [24]:
# Вывести общую информацию о датасете
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 271116 entries, 0 to 271115
Data columns (total 15 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   ID      271116 non-null  int64
 1   Name    271116 non-null  str
 2   Sex     271116 non-null  str
 3   Age     261642 non-null  float64
 4   Height  210945 non-null  float64
 5   Weight  208241 non-null  float64
 6   Team    271116 non-null  str
 7   NOC     271116 non-null  str
 8   Games   271116 non-null  str
 9   Year    271116 non-null  int64
 10  Season  271116 non-null  str
 11  City    271116 non-null  str
 12  Sport   271116 non-null  str
 13  Event   271116 non-null  str
 14  Medal   39783 non-null   str
dtypes: float64(3), int64(2), str(10)
memory usage: 31.0 MB

In [25]:
# Вывести размер датасета (количество строк и столбцов)
df.shape

(271116, 15)

In [26]:
# Вывести 10-ю строку
df.iloc[10]

ID                                               6
Name                               Per Knut Aaland
Sex                                              M
Age                                           31.0
Height                                       188.0
Weight                                        75.0
Team                                 United States
NOC                                            USA
Games                                  1992 Winter
Year                                          1992
Season                                      Winter
City                                   Albertville
Sport                         Cross Country Skiing
Event     Cross Country Skiing Men's 10 kilometres
Medal                                          NaN
Name: 10, dtype: object

In [27]:
# Вывести столбцы Team, NOC, Games
df[['Team', 'NOC', 'Games']]

                  Team  NOC        Games
0                China  CHN  1992 Summer
1                China  CHN  2012 Summer
2              Denmark  DEN  1920 Summer
3       Denmark/Sweden  DEN  1900 Summer
4          Netherlands  NED  1988 Winter
...                ...  ...          ...
271111        Poland-1  POL  1976 Winter
271112          Poland  POL  2014 Winter
271113          Poland  POL  2014 Winter
271114          Poland  POL  1998 Winter
271115          Poland  POL  2002 Winter

[271116 rows x 3 columns]

In [28]:
# Вывести для столбцов Team, NOC, Games строки со 2 по 15
df.loc[1:14, ['Team', 'NOC', 'Games']]

              Team  NOC        Games
1            China  CHN  2012 Summer
2          Denmark  DEN  1920 Summer
3   Denmark/Sweden  DEN  1900 Summer
4      Netherlands  NED  1988 Winter
5      Netherlands  NED  1988 Winter
6      Netherlands  NED  1992 Winter
7      Netherlands  NED  1992 Winter
8      Netherlands  NED  1994 Winter
9      Netherlands  NED  1994 Winter
10   United States  USA  1992 Winter
11   United States  USA  1992 Winter
12   United States  USA  1992 Winter
13   United States  USA  1992 Winter
14   United States  USA  1994 Winter

In [29]:
# Вывести данные о спортсменах моложе 16 лет
df[df['Age'] < 16]

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
265,137,Giordano Giulio Abbondati,M,15.0,175.0,64.0,Italy,ITA,1964 Winter,1964,Winter,Innsbruck,Figure Skating,Figure Skating Men's Singles,NaN
295,159,Reem Wa'il Abdalazem Abdalazem El-Bossaty,F,15.0,167.0,60.0,Egypt,EGY,2008 Summer,2008,Summer,Beijing,Synchronized Swimming,Synchronized Swimming Women's Duet,NaN
296,159,Reem Wa'il Abdalazem Abdalazem El-Bossaty,F,15.0,167.0,60.0,Egypt,EGY,2008 Summer,2008,Summer,Beijing,Synchronized Swimming,Synchronized Swimming Women's Team,NaN
517,290,Fatima Abdul Majeed Hameed Al-Kirashi,F,14.0,NaN,NaN,Bahrain,BRN,2000 Summer,2000,Summer,Sydney,Swimming,Swimming Women's 50 metres Freestyle,NaN
600,346,Shaza Yahia Nazih Abdulrahman El-Sayed,F,15.0,170.0,59.0,Egypt,EGY,2008 Summer,2008,Summer,Beijing,Synchronized Swimming,Synchronized Swimming Women's Team,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
269658,134939,Miriam Ziegler,F,15.0,154.0,47.0,Austria,AUT,2010 Winter,2010,Winter,Vancouver,Figure Skating,Figure Skating Women's Singles,NaN
269824,135002,Eileen Zillmer,F,15.0,170.0,49.0,West Germany,FRG,1968 Winter,1968,Winter,Grenoble,Figure Skating,Figure Skating Women's Singles,NaN
270856,135462,Bernadette Zurbriggen,F,15.0,173.0,66.0,Switzerland,SUI,1972 Winter,1972,Winter,Sapporo,Alpine Skiing,Alpine Skiing Women's Downhill,NaN
270857,135462,Bernadette Zurbriggen,F,15.0,173.0,66.0,Switzerland,SUI,1972 Winter,1972,Winter,Sapporo,Alpine Skiing,Alpine Skiing Women's Giant Slalom,NaN
270858,135462,Bernadette Zurbriggen,F,15.0,173.0,66.0,Switzerland,SUI,1972 Winter,1972,Winter,Sapporo,Alpine Skiing,Alpine Skiing Women's Slalom,NaN

In [30]:
# Вывести данные о спортсменах из России
df[df['NOC'] == 'RUS']

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
163,67,Mariya Vasilyevna Abakumova (-Tarabina),F,22.0,179.0,80.0,Russia,RUS,2008 Summer,2008,Summer,Beijing,Athletics,Athletics Women's Javelin Throw,Silver
164,67,Mariya Vasilyevna Abakumova (-Tarabina),F,26.0,179.0,80.0,Russia,RUS,2012 Summer,2012,Summer,London,Athletics,Athletics Women's Javelin Throw,NaN
195,90,Tamila Rashidovna Abasova,F,21.0,163.0,60.0,Russia,RUS,2004 Summer,2004,Summer,Athina,Cycling,Cycling Women's Sprint,Silver
196,90,Tamila Rashidovna Abasova,F,21.0,163.0,60.0,Russia,RUS,2004 Summer,2004,Summer,Athina,Cycling,Cycling Women's 500 metres Time Trial,NaN
615,356,Adlan Aliyevich Abdurashidov,M,26.0,172.0,60.0,Russia,RUS,2016 Summer,2016,Summer,Rio de Janeiro,Boxing,Boxing Men's Lightweight,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271102,135563,Olesya Nikolayevna Zykina,F,19.0,171.0,64.0,Russia,RUS,2000 Summer,2000,Summer,Sydney,Athletics,Athletics Women's 4 x 400 metres Relay,Bronze
271103,135563,Olesya Nikolayevna Zykina,F,23.0,171.0,64.0,Russia,RUS,2004 Summer,2004,Summer,Athina,Athletics,Athletics Women's 4 x 400 metres Relay,Silver
271104,135564,Yevgeny Aleksandrovich Zykov,M,22.0,172.0,65.0,Russia-1,RUS,2002 Winter,2002,Winter,Salt Lake City,Luge,Luge Mixed (Men)'s Doubles,NaN
271108,135567,Aleksandr Viktorovich Zyuzin,M,24.0,183.0,72.0,Russia,RUS,2000 Summer,2000,Summer,Sydney,Rowing,Rowing Men's Lightweight Coxless Fours,NaN
271109,135567,Aleksandr Viktorovich Zyuzin,M,28.0,183.0,72.0,Russia,RUS,2004 Summer,2004,Summer,Athina,Rowing,Rowing Men's Lightweight Coxless Fours,NaN

In [31]:
#вариант 2
#Россия + СССР + Российская империя (Все исторические периоды)
df[df['NOC'].isin(['RUS', 'URS', 'RU1'])]

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
163,67,Mariya Vasilyevna Abakumova (-Tarabina),F,22.0,179.0,80.0,Russia,RUS,2008 Summer,2008,Summer,Beijing,Athletics,Athletics Women's Javelin Throw,Silver
164,67,Mariya Vasilyevna Abakumova (-Tarabina),F,26.0,179.0,80.0,Russia,RUS,2012 Summer,2012,Summer,London,Athletics,Athletics Women's Javelin Throw,NaN
192,87,Rost'om Omeris dze Abashidze,M,29.0,188.0,97.0,Soviet Union,URS,1964 Summer,1964,Summer,Tokyo,Wrestling,"Wrestling Men's Light-Heavyweight, Greco-Roman",NaN
193,88,Nunu Dzhansuhivna Abashydze (-Myslaieva),F,25.0,168.0,105.0,Soviet Union,URS,1980 Summer,1980,Summer,Moskva,Athletics,Athletics Women's Shot Put,NaN
195,90,Tamila Rashidovna Abasova,F,21.0,163.0,60.0,Russia,RUS,2004 Summer,2004,Summer,Athina,Cycling,Cycling Women's Sprint,Silver
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271102,135563,Olesya Nikolayevna Zykina,F,19.0,171.0,64.0,Russia,RUS,2000 Summer,2000,Summer,Sydney,Athletics,Athletics Women's 4 x 400 metres Relay,Bronze
271103,135563,Olesya Nikolayevna Zykina,F,23.0,171.0,64.0,Russia,RUS,2004 Summer,2004,Summer,Athina,Athletics,Athletics Women's 4 x 400 metres Relay,Silver
271104,135564,Yevgeny Aleksandrovich Zykov,M,22.0,172.0,65.0,Russia-1,RUS,2002 Winter,2002,Winter,Salt Lake City,Luge,Luge Mixed (Men)'s Doubles,NaN
271108,135567,Aleksandr Viktorovich Zyuzin,M,24.0,183.0,72.0,Russia,RUS,2000 Summer,2000,Summer,Sydney,Rowing,Rowing Men's Lightweight Coxless Fours,NaN
271109,135567,Aleksandr Viktorovich Zyuzin,M,28.0,183.0,72.0,Russia,RUS,2004 Summer,2004,Summer,Athina,Rowing,Rowing Men's Lightweight Coxless Fours,NaN

In [32]:
# Вывести на экран золотых медалистов 2012 года
df[(df['Year'] == 2012) & (df['Medal'] == 'Gold')]

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
174,73,Luc Abalo,M,27.0,182.0,86.0,France,FRA,2012 Summer,2012,Summer,London,Handball,Handball Men's Handball,Gold
1126,629,William Accambray,M,24.0,194.0,104.0,France,FRA,2012 Summer,2012,Summer,London,Handball,Handball Men's Handball,Gold
1494,832,Nicola Virginia Adams,F,29.0,164.0,51.0,Great Britain,GBR,2012 Summer,2012,Summer,London,Boxing,Boxing Women's Flyweight,Gold
1528,846,Valerie Kasanita Adams-Vili (-Price),F,27.0,193.0,120.0,New Zealand,NZL,2012 Summer,2012,Summer,London,Athletics,Athletics Women's Shot Put,Gold
1533,849,Filip Kamil Adamski,M,29.0,189.0,87.0,Germany,GER,2012 Summer,2012,Summer,London,Rowing,Rowing Men's Coxed Eights,Gold
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270306,135219,Urka olnir,F,30.0,173.0,64.0,Slovenia,SLO,2012 Summer,2012,Summer,London,Judo,Judo Women's Half-Middleweight,Gold
270326,135228,Epke Jan Zonderland,M,26.0,173.0,69.0,Netherlands,NED,2012 Summer,2012,Summer,London,Gymnastics,Gymnastics Men's Horizontal Bar,Gold
270434,135269,Zou Kai,M,24.0,158.0,55.0,China,CHN,2012 Summer,2012,Summer,London,Gymnastics,Gymnastics Men's Team All-Around,Gold
270435,135269,Zou Kai,M,24.0,158.0,55.0,China,CHN,2012 Summer,2012,Summer,London,Gymnastics,Gymnastics Men's Floor Exercise,Gold
270440,135270,Zou Shiming,M,31.0,165.0,49.0,China,CHN,2012 Summer,2012,Summer,London,Boxing,Boxing Men's Light-Flyweight,Gold

In [33]:
# Вывести на экран имена золотых медалистов 2012 года
df[(df['Year'] == 2012) & (df['Medal'] == 'Gold')]['Name']

174                                  Luc Abalo
1126                         William Accambray
1494                     Nicola Virginia Adams
1528      Valerie Kasanita Adams-Vili (-Price)
1533                       Filip Kamil Adamski
                          ...
270306                              Urka olnir
270326                     Epke Jan Zonderland
270434                                 Zou Kai
270435                                 Zou Kai
270440                             Zou Shiming
Name: Name, Length: 632, dtype: str

In [34]:
# Вывести все заполненные строки таблицы и сохранить в файл notnull_athlete.xlsx
# 1. Удаляем все строки, где есть хотя бы одно пустое значение (NaN)
df_clean = df.dropna()

# 2. Сохраняем очищенную таблицу в файл Excel без порядковых индексов
df_clean.to_excel('notnull_athlete.xlsx', index=False)

In [35]:
# Средний возраст спортсменов
df['Age'].mean()

np.float64(25.556898357297374)

In [36]:
# Минимальный возраст спортсменов
df['Age'].min()

np.float64(10.0)

In [37]:
# Максимальный возраст спортсменов
df['Age'].max()

np.float64(97.0)

In [38]:
# Год первой и последней Олимпиаде в датасете
# Находим год первой и последней Олимпиады
first_olympic = df['Year'].min()
last_olympic = df['Year'].max()

print("Год первой Олимпиады:", first_olympic)
print("Год последней Олимпиады:", last_olympic)

Год первой Олимпиады: 1896
Год последней Олимпиады: 2016

In [39]:
# Cамый "тяжелый" спортсмен за всю историю Олимпиад
# 1. Находим максимальный вес в таблице
max_weight = df['Weight'].max()

# 2. Выводим всю информацию о спортсмене с таким весом
df[df['Weight'] == max_weight]

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
23155,12177,"Ricardo Blas, Jr.",M,21.0,183.0,214.0,Guam,GUM,2008 Summer,2008,Summer,Beijing,Judo,Judo Men's Heavyweight,NaN
23156,12177,"Ricardo Blas, Jr.",M,25.0,183.0,214.0,Guam,GUM,2012 Summer,2012,Summer,London,Judo,Judo Men's Heavyweight,NaN

In [40]:
# В каком виде спорта участвовал самый высокий спортсмен?
# Находим строку со спортсменом, у которого максимальный рост (Height)
df[df['Height'] == df['Height'].max()][['Name', 'Sport', 'NOC', 'Height', 'Weight']]

            Name       Sport  NOC  Height  Weight
265040  Yao Ming  Basketball  CHN   226.0   141.0
265041  Yao Ming  Basketball  CHN   226.0   141.0
265042  Yao Ming  Basketball  CHN   226.0   141.0

In [41]:
# Сколько спортсменов участвовало в каждом виде спорта?
df['Sport'].value_counts()

Sport
Athletics        38624
Gymnastics       26707
Swimming         23195
Shooting         11448
Cycling          10859
                 ...
Racquets            12
Jeu De Paume        11
Roque                4
Basque Pelota        2
Aeronautics          1
Name: count, Length: 66, dtype: int64

In [42]:
# Как часто страны участвовали в Олимпиаде?
# Группируем по коду страны (NOC) и считаем уникальные года (Year)
country_participation = df.groupby('NOC')['Year'].nunique().sort_values(ascending=False)

# Выводим результат
country_participation

NOC
ITA    35
FRA    35
GBR    35
GRE    35
SUI    35
       ..
ROT     1
UNK     1
UAR     1
WIF     1
YMD     1
Name: Year, Length: 230, dtype: int64

In [43]:
# Вывести количество мужчин и женщин, участвующих в Олимпиаде 2012 года
# Фильтруем данные по 2012 году и считаем количество мужчин (M) и женщин (F)
df[df['Year'] == 2012]['Sex'].value_counts()

Sex
M    7105
F    5815
Name: count, dtype: int64

In [44]:
# Вывести количество призеров первой и последней Олимпиады
# 1. Находим годы первой и последней Олимпиад в истории
first_year = df['Year'].min()
last_year = df['Year'].max()

# 2. Фильтруем строки, где есть медали (исключаем пустые значения NaN)
df_medals = df[df['Medal'].notnull()]

# 3. Считаем количество призеров для каждого из этих двух годов
first_medals_count = df_medals[df_medals['Year'] == first_year].shape[0]
last_medals_count = df_medals[df_medals['Year'] == last_year].shape[0]

print(f"Количество призеров на первой Олимпиаде ({first_year} год):", first_medals_count)
print(f"Количество призеров на последней Олимпиаде ({last_year} год):", last_medals_count)

Количество призеров на первой Олимпиаде (1896 год): 143
Количество призеров на последней Олимпиаде (2016 год): 2023

In [45]:
# Рассчитываем сколько всего во всех дисциплинах золотых медалей получила Россия в 2016 году
# Фильтруем данные по России (RUS), 2016 году и золотым медалям (Gold)
russia_gold_2016 = df[(df['NOC'] == 'RUS') & (df['Year'] == 2016) & (df['Medal'] == 'Gold')]

# Считаем количество записей
russia_gold_2016.shape[0]

52

In [46]:
# Количество командных дисциплин и соревнований, где Россия выиграла золото
# Выводим уникальные дисциплины, в которых Россия взяла золото в 2016
russia_gold_2016[['Event', 'Sport']].drop_duplicates()

                                                 Event                  Sport
2961                          Fencing Men's Foil, Team                Fencing
22308                Rhythmic Gymnastics Women's Group    Rhythmic Gymnastics
23362                        Handball Women's Handball               Handball
38115   Wrestling Men's Light-Heavyweight, Greco-Roman              Wrestling
40261               Synchronized Swimming Women's Team  Synchronized Swimming
54025                 Fencing Women's Foil, Individual                Fencing
60572                      Fencing Women's Sabre, Team                Fencing
103712              Synchronized Swimming Women's Duet  Synchronized Swimming
116787                    Judo Men's Half-Middleweight                   Judo
137305              Modern Pentathlon Men's Individual      Modern Pentathlon
147098                          Tennis Women's Doubles                 Tennis
147990          Rhythmic Gymnastics Women's Individual    Rhythmic Gymnastics
164991                    Judo Men's Extra-Lightweight                   Judo
166660                  Gymnastics Women's Uneven Bars             Gymnastics
196594         Wrestling Men's Welterweight, Freestyle              Wrestling
207589    Wrestling Men's Light-Heavyweight, Freestyle              Wrestling
240488                        Boxing Men's Heavyweight                 Boxing
253572       Wrestling Men's Middleweight, Greco-Roman              Wrestling
265365               Fencing Women's Sabre, Individual                Fencing

In [47]:
# Находим количество уникальных соревнований (Event), где у России в 2016 было золото
df[(df['NOC'] == 'RUS') & (df['Year'] == 2016) & (df['Medal'] == 'Gold')]['Event'].nunique()

19