# Основы Pandas. Часть 2

In [1]:
import pandas as pd

In [2]:
df1 = pd.read_excel('B2B.xlsx', sheet_name='Лист1')
df1

                                ФИО                      Почта
0            Нистряну Олег Олегович    NistrianuOO@sibgenco.ru
1         Гришанова Оксана Павловна   GrishanovaOP@sibgenco.ru
2    Денисова Татьяна Александровна   DenisovaTatA@sibgenco.ru
3      Полева Александра Дмитриевна       PolevaAD@sibgenco.ru
4       Бурмакина Оксана Викторовна    BurmakinaOV@sibgenco.ru
..                              ...                        ...
614      Никитина Юлия Искандеровна    NikitinaIuI@sibgenco.ru
615       Азаренко Никита Сергеевич     AzarenkoNS@sibgenco.ru
616    Ковалёва Виктория Викторовна     KovalevaVV@sibgenco.ru
617       Киселева Дарья Алексеевна     KiselevaDA@sibgenco.ru
618        Ночевская Ирина Олеговна  NochevskayaIO@sibgenco.ru

[619 rows x 2 columns]

In [3]:
df2 = pd.read_excel('B2B.xlsx', sheet_name='Лист2', header= None)
df2

                                  0                                 1
0          Новиков Алексей Игоревич   aleksey.novikov@pte.eurochem.ru
1       Швецов Александр Алексеевич  Aleksandr.A.Shvetsov@eurochem.ru
2             Абрамовский Ян Патрис             Yan.Abramovsky@grk.ru
3      Бугаева Светлана Геннадьевна           Svetlana.Bugaeva@grk.ru
4         Гавриленко Юлия Сергеевна          Yuliya.Gavrilenko@grk.ru
..                              ...                               ...
321       Смирнов Евгений Сергеевич       Evgeniy.Smirnov@eurochem.ru
322     Абраменко Олеся Темуразовна                AbramenkoOT@grk.ru
323  Кирпичева Марина Станиславовна          Marina.Kirpicheva@grk.ru
324     Коновалов Алексей Сергеевич          Aleksei.Konovalov@grk.ru
325     Хохлачев Дмитрий Дмитриевич              KhokhlachevDD@grk.ru

[326 rows x 2 columns]

In [5]:
full_df = pd.concat([df1,df2])
full_df

,ФИО,Почта,0,1
0,Нистряну Олег Олегович,NistrianuOO@sibgenco.ru,NaN,NaN
1,Гришанова Оксана Павловна,GrishanovaOP@sibgenco.ru,NaN,NaN
2,Денисова Татьяна Александровна,DenisovaTatA@sibgenco.ru,NaN,NaN
3,Полева Александра Дмитриевна,PolevaAD@sibgenco.ru,NaN,NaN
4,Бурмакина Оксана Викторовна,BurmakinaOV@sibgenco.ru,NaN,NaN
...,...,...,...,...
321,NaN,NaN,Смирнов Евгений Сергеевич,Evgeniy.Smirnov@eurochem.ru
322,NaN,NaN,Абраменко Олеся Темуразовна,AbramenkoOT@grk.ru
323,NaN,NaN,Кирпичева Марина Станиславовна,Marina.Kirpicheva@grk.ru
324,NaN,NaN,Коновалов Алексей Сергеевич,Aleksei.Konovalov@grk.ru
325,NaN,NaN,Хохлачев Дмитрий Дмитриевич,KhokhlachevDD@grk.ru

In [ ]:
full_df = pd.concat([df1,df2])
full_df

In [6]:
df2 = pd.read_excel('B2B.xlsx', sheet_name = 'Лист2', header = None, names = ['ФИО', 'Почта'])
df2

                                ФИО                             Почта
0          Новиков Алексей Игоревич   aleksey.novikov@pte.eurochem.ru
1       Швецов Александр Алексеевич  Aleksandr.A.Shvetsov@eurochem.ru
2             Абрамовский Ян Патрис             Yan.Abramovsky@grk.ru
3      Бугаева Светлана Геннадьевна           Svetlana.Bugaeva@grk.ru
4         Гавриленко Юлия Сергеевна          Yuliya.Gavrilenko@grk.ru
..                              ...                               ...
321       Смирнов Евгений Сергеевич       Evgeniy.Smirnov@eurochem.ru
322     Абраменко Олеся Темуразовна                AbramenkoOT@grk.ru
323  Кирпичева Марина Станиславовна          Marina.Kirpicheva@grk.ru
324     Коновалов Алексей Сергеевич          Aleksei.Konovalov@grk.ru
325     Хохлачев Дмитрий Дмитриевич              KhokhlachevDD@grk.ru

[326 rows x 2 columns]

In [7]:
full_df2 = pd.concat([df1, df2])
full_df2

                                ФИО                        Почта
0            Нистряну Олег Олегович      NistrianuOO@sibgenco.ru
1         Гришанова Оксана Павловна     GrishanovaOP@sibgenco.ru
2    Денисова Татьяна Александровна     DenisovaTatA@sibgenco.ru
3      Полева Александра Дмитриевна         PolevaAD@sibgenco.ru
4       Бурмакина Оксана Викторовна      BurmakinaOV@sibgenco.ru
..                              ...                          ...
321       Смирнов Евгений Сергеевич  Evgeniy.Smirnov@eurochem.ru
322     Абраменко Олеся Темуразовна           AbramenkoOT@grk.ru
323  Кирпичева Марина Станиславовна     Marina.Kirpicheva@grk.ru
324     Коновалов Алексей Сергеевич     Aleksei.Konovalov@grk.ru
325     Хохлачев Дмитрий Дмитриевич         KhokhlachevDD@grk.ru

[945 rows x 2 columns]

In [8]:
full_df2 = pd.concat([df1, df2], axis = 1)
full_df2

,ФИО,Почта,ФИО,Почта
0,Нистряну Олег Олегович,NistrianuOO@sibgenco.ru,Новиков Алексей Игоревич,aleksey.novikov@pte.eurochem.ru
1,Гришанова Оксана Павловна,GrishanovaOP@sibgenco.ru,Швецов Александр Алексеевич,Aleksandr.A.Shvetsov@eurochem.ru
2,Денисова Татьяна Александровна,DenisovaTatA@sibgenco.ru,Абрамовский Ян Патрис,Yan.Abramovsky@grk.ru
3,Полева Александра Дмитриевна,PolevaAD@sibgenco.ru,Бугаева Светлана Геннадьевна,Svetlana.Bugaeva@grk.ru
4,Бурмакина Оксана Викторовна,BurmakinaOV@sibgenco.ru,Гавриленко Юлия Сергеевна,Yuliya.Gavrilenko@grk.ru
...,...,...,...,...
614,Никитина Юлия Искандеровна,NikitinaIuI@sibgenco.ru,NaN,NaN
615,Азаренко Никита Сергеевич,AzarenkoNS@sibgenco.ru,NaN,NaN
616,Ковалёва Виктория Викторовна,KovalevaVV@sibgenco.ru,NaN,NaN
617,Киселева Дарья Алексеевна,KiselevaDA@sibgenco.ru,NaN,NaN
618,Ночевская Ирина Олеговна,NochevskayaIO@sibgenco.ru,NaN,NaN

In [10]:
full_df2 = pd.concat([df1, df2], ignore_index=True)
full_df2

                                ФИО                        Почта
0            Нистряну Олег Олегович      NistrianuOO@sibgenco.ru
1         Гришанова Оксана Павловна     GrishanovaOP@sibgenco.ru
2    Денисова Татьяна Александровна     DenisovaTatA@sibgenco.ru
3      Полева Александра Дмитриевна         PolevaAD@sibgenco.ru
4       Бурмакина Оксана Викторовна      BurmakinaOV@sibgenco.ru
..                              ...                          ...
940       Смирнов Евгений Сергеевич  Evgeniy.Smirnov@eurochem.ru
941     Абраменко Олеся Темуразовна           AbramenkoOT@grk.ru
942  Кирпичева Марина Станиславовна     Marina.Kirpicheva@grk.ru
943     Коновалов Алексей Сергеевич     Aleksei.Konovalov@grk.ru
944     Хохлачев Дмитрий Дмитриевич         KhokhlachevDD@grk.ru

[945 rows x 2 columns]

In [14]:
full_df2.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
940     True
941     True
942     True
943     True
944     True
Length: 945, dtype: bool

In [13]:
full_df2.duplicated().sum()

np.int64(325)

In [15]:
full_df2.nunique()

ФИО      619
Почта    619
dtype: int64

In [16]:
full_df2.ФИО.nunique()

619

In [17]:
full_df2.nunique()

ФИО      619
Почта    619
dtype: int64

In [19]:
full_df2[full_df2.ФИО.isna()]

     ФИО                      Почта
586  NaN  a.gorbaneva@b2b-center.ru

In [20]:
full_df2['ФИО'] = full_df2['ФИО'].fillna('Горбанева Анастасия')
full_df2.iloc[586, :]

ФИО            Горбанева Анастасия
Почта    a.gorbaneva@b2b-center.ru
Name: 586, dtype: str

In [22]:
partner_df1 = pd.read_csv('partner_data.csv')
partner_df1

,id,age,job,marital,education,balance,housing,loan,default
0,1,26.0,unemployed,married,tertiary,454,yes,yes,no
1,2,25.0,technician,married,secondary,517,no,no,no
2,3,36.0,technician,single,secondary,1044,yes,no,no
3,4,45.0,blue-collar,married,secondary,146,yes,yes,no
4,5,27.0,management,married,tertiary,145,no,no,no
...,...,...,...,...,...,...,...,...,...
995,996,41.0,entrepreneur,married,secondary,-1882,yes,no,no
996,997,58.0,management,married,tertiary,1271,yes,no,no
997,998,31.0,services,single,secondary,297,no,no,no
998,999,31.0,entrepreneur,NaN,tertiary,312,no,no,no
999,1000,23.0,blue-collar,single,secondary,780,yes,no,no

In [23]:
partner_df2 = pd.read_csv('partner_data_next_part.csv')
partner_df2

     id            job   marital  education  balance housing loan default
0  1001     technician       NaN   tertiary        0      no   no     yes
1  1002    blue-collar   married    primary      300     yes   no      no
2  1003     management   married   tertiary       15     yes   no      no
3  1004    blue-collar    single    primary     -100     yes   no      no
4  1005       services  divorced  secondary      430     yes  yes     yes
5  1006     management   married   tertiary     2071     yes   no      no
6  1007   entrepreneur   married  secondary    -1882      no   no      no
7  1008        unknown    single    unknown     1819      no   no      no
8  1009  self-employed       NaN  secondary      146     yes   no      no
9  1010       services    single  secondary      297      no   no      no

In [24]:
total = partner_df1.merge(partner_df2)
total

Empty DataFrame
Columns: [id, age, job, marital, education, balance, housing, loan, default]
Index: []

In [25]:
total = partner_df1.merge(partner_df2, how= 'inner')
total

Empty DataFrame
Columns: [id, age, job, marital, education, balance, housing, loan, default]
Index: []

In [26]:
total = partner_df1.merge(partner_df2, how= 'outer')
total

,id,age,job,marital,education,balance,housing,loan,default
0,1,26.0,unemployed,married,tertiary,454,yes,yes,no
1,2,25.0,technician,married,secondary,517,no,no,no
2,3,36.0,technician,single,secondary,1044,yes,no,no
3,4,45.0,blue-collar,married,secondary,146,yes,yes,no
4,5,27.0,management,married,tertiary,145,no,no,no
...,...,...,...,...,...,...,...,...,...
1005,1006,NaN,management,married,tertiary,2071,yes,no,no
1006,1007,NaN,entrepreneur,married,secondary,-1882,no,no,no
1007,1008,NaN,unknown,single,unknown,1819,no,no,no
1008,1009,NaN,self-employed,NaN,secondary,146,yes,no,no
1009,1010,NaN,services,single,secondary,297,no,no,no

In [27]:
total = partner_df1.merge(partner_df2, how= 'left')
total

,id,age,job,marital,education,balance,housing,loan,default
0,1,26.0,unemployed,married,tertiary,454,yes,yes,no
1,2,25.0,technician,married,secondary,517,no,no,no
2,3,36.0,technician,single,secondary,1044,yes,no,no
3,4,45.0,blue-collar,married,secondary,146,yes,yes,no
4,5,27.0,management,married,tertiary,145,no,no,no
...,...,...,...,...,...,...,...,...,...
995,996,41.0,entrepreneur,married,secondary,-1882,yes,no,no
996,997,58.0,management,married,tertiary,1271,yes,no,no
997,998,31.0,services,single,secondary,297,no,no,no
998,999,31.0,entrepreneur,NaN,tertiary,312,no,no,no
999,1000,23.0,blue-collar,single,secondary,780,yes,no,no

In [28]:
total = partner_df1.merge(partner_df2, how= 'right')
total

     id  age            job   marital  education  balance housing loan default
0  1001  NaN     technician       NaN   tertiary        0      no   no     yes
1  1002  NaN    blue-collar   married    primary      300     yes   no      no
2  1003  NaN     management   married   tertiary       15     yes   no      no
3  1004  NaN    blue-collar    single    primary     -100     yes   no      no
4  1005  NaN       services  divorced  secondary      430     yes  yes     yes
5  1006  NaN     management   married   tertiary     2071     yes   no      no
6  1007  NaN   entrepreneur   married  secondary    -1882      no   no      no
7  1008  NaN        unknown    single    unknown     1819      no   no      no
8  1009  NaN  self-employed       NaN  secondary      146     yes   no      no
9  1010  NaN       services    single  secondary      297      no   no      no

In [29]:
total = partner_df1.merge(partner_df2, how= 'outer')
total

,id,age,job,marital,education,balance,housing,loan,default
0,1,26.0,unemployed,married,tertiary,454,yes,yes,no
1,2,25.0,technician,married,secondary,517,no,no,no
2,3,36.0,technician,single,secondary,1044,yes,no,no
3,4,45.0,blue-collar,married,secondary,146,yes,yes,no
4,5,27.0,management,married,tertiary,145,no,no,no
...,...,...,...,...,...,...,...,...,...
1005,1006,NaN,management,married,tertiary,2071,yes,no,no
1006,1007,NaN,entrepreneur,married,secondary,-1882,no,no,no
1007,1008,NaN,unknown,single,unknown,1819,no,no,no
1008,1009,NaN,self-employed,NaN,secondary,146,yes,no,no
1009,1010,NaN,services,single,secondary,297,no,no,no

In [30]:
partner_df3 = pd.read_csv('other_partner_data.csv')
partner_df3

       id gender
0       1  women
1       2  women
2       3    man
3       5    man
4       6    man
..    ...    ...
705  1006  women
706  1007    man
707  1008    man
708  1009  women
709  1010  women

[710 rows x 2 columns]

In [31]:
partner_df3.id.values

array([   1,    2,    3,    5,    6,    7,    9,   11,   12,   13,   14,
         15,   16,   17,   18,   19,   20,   21,   26,   28,   29,   30,
         31,   33,   34,   36,   37,   38,   39,   40,   43,   47,   48,
         49,   50,   51,   52,   54,   55,   57,   58,   59,   61,   63,
         65,   66,   68,   70,   71,   72,   73,   74,   76,   81,   82,
         83,   85,   87,   88,   90,   91,   92,   93,   94,   96,   99,
        100,  102,  103,  105,  108,  109,  110,  113,  114,  115,  116,
        117,  118,  119,  121,  122,  123,  125,  126,  127,  128,  129,
        132,  133,  134,  135,  137,  138,  139,  141,  142,  143,  144,
        146,  147,  148,  149,  150,  151,  153,  154,  155,  156,  158,
        159,  161,  163,  164,  165,  167,  168,  170,  172,  174,  175,
        176,  178,  180,  181,  184,  186,  187,  188,  190,  191,  192,
        193,  196,  197,  199,  202,  204,  205,  206,  207,  208,  209,
        210,  211,  214,  215,  216,  218,  219,  220,  221,  222,  224,
        229,  230,  231,  232,  234,  237,  238,  240,  241,  243,  245,
        246,  247,  248,  249,  250,  251,  252,  254,  255,  256,  257,
        258,  260,  262,  263,  264,  265,  271,  272,  274,  277,  278,
        280,  281,  282,  283,  285,  286,  288,  290,  291,  294,  297,
        299,  301,  302,  303,  305,  306,  307,  309,  311,  312,  313,
        314,  316,  319,  321,  322,  325,  327,  328,  329,  331,  333,
        334,  335,  338,  339,  342,  343,  344,  345,  346,  347,  348,
        350,  351,  352,  354,  356,  357,  358,  360,  363,  364,  365,
        366,  368,  369,  370,  372,  373,  375,  376,  377,  378,  379,
        381,  383,  385,  386,  387,  388,  389,  390,  391,  393,  394,
        397,  398,  399,  400,  402,  403,  404,  405,  406,  407,  408,
        410,  412,  413,  414,  416,  417,  418,  419,  421,  422,  423,
        424,  425,  428,  429,  432,  433,  434,  436,  437,  439,  440,
        441,  442,  444,  445,  446,  447,  448,  449,  450,  456,  457,
        458,  459,  460,  461,  462,  463,  464,  468,  469,  470,  471,
        472,  473,  475,  477,  480,  482,  483,  484,  485,  486,  488,
        490,  491,  492,  493,  494,  495,  496,  498,  500,  502,  503,
        505,  506,  508,  509,  512,  513,  515,  517,  518,  520,  521,
        522,  524,  525,  526,  527,  528,  529,  530,  531,  533,  534,
        539,  540,  541,  542,  545,  546,  547,  548,  551,  552,  553,
        554,  555,  557,  558,  559,  560,  561,  562,  563,  564,  568,
        569,  570,  571,  573,  574,  575,  576,  577,  578,  579,  580,
        581,  584,  585,  587,  588,  589,  590,  592,  595,  596,  598,
        599,  600,  601,  602,  603,  605,  606,  608,  610,  612,  613,
        614,  615,  616,  617,  620,  622,  623,  624,  625,  626,  629,
        632,  633,  634,  635,  636,  637,  640,  641,  643,  644,  646,
        647,  648,  651,  652,  653,  654,  655,  656,  658,  661,  663,
        664,  666,  667,  669,  671,  673,  674,  676,  677,  679,  681,
        682,  683,  684,  685,  687,  688,  690,  691,  693,  695,  696,
        697,  700,  701,  702,  703,  704,  705,  707,  709,  710,  711,
        712,  713,  714,  715,  716,  720,  722,  723,  725,  726,  727,
        728,  729,  730,  731,  733,  734,  735,  736,  737,  739,  740,
        742,  744,  745,  746,  747,  748,  749,  750,  751,  752,  754,
        756,  760,  761,  762,  763,  764,  765,  768,  770,  771,  772,
        773,  774,  777,  780,  781,  782,  784,  785,  787,  788,  790,
        791,  792,  795,  797,  799,  802,  803,  806,  807,  808,  809,
        811,  813,  814,  815,  816,  819,  820,  822,  823,  824,  825,
        826,  827,  830,  831,  832,  833,  835,  836,  838,  839,  840,
        841,  842,  844,  846,  847,  848,  849,  850,  852,  853,  855,
        856,  857,  859,  860,  861,  862,  863,  864,  865,  866,  867,
        868,  869,  871,  875,  876,  877,  878,  879,  881,  883,  884,
        885,  886,  888,  890,  891,  892,  893,  894,  895,  896,  897,
        898,  900,  901,  903,  904,  905,  906,  907,  909,  910,  911,
        912,  913,  914,  915,  917,  918,  920,  921,  922,  923,  924,
        925,  927,  928,  929,  930,  931,  932,  933,  934,  938,  939,
        940,  941,  942,  943,  944,  945,  946,  947,  948,  949,  951,
        953,  954,  955,  958,  959,  960,  961,  962,  963,  964,  965,
        966,  967,  968,  969,  970,  971,  972,  973,  977,  978,  979,
        980,  981,  982,  983,  984,  985,  986,  987,  989,  990,  991,
        992,  993,  995,  996,  997,  999, 1000, 1001, 1002, 1003, 1004,
       1005, 1006, 1007, 1008, 1009, 1010])

In [32]:
partner_df3.id.values.tolist()

[1,
 2,
 3,
 5,
 6,
 7,
 9,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 26,
 28,
 29,
 30,
 31,
 33,
 34,
 36,
 37,
 38,
 39,
 40,
 43,
 47,
 48,
 49,
 50,
 51,
 52,
 54,
 55,
 57,
 58,
 59,
 61,
 63,
 65,
 66,
 68,
 70,
 71,
 72,
 73,
 74,
 76,
 81,
 82,
 83,
 85,
 87,
 88,
 90,
 91,
 92,
 93,
 94,
 96,
 99,
 100,
 102,
 103,
 105,
 108,
 109,
 110,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 121,
 122,
 123,
 125,
 126,
 127,
 128,
 129,
 132,
 133,
 134,
 135,
 137,
 138,
 139,
 141,
 142,
 143,
 144,
 146,
 147,
 148,
 149,
 150,
 151,
 153,
 154,
 155,
 156,
 158,
 159,
 161,
 163,
 164,
 165,
 167,
 168,
 170,
 172,
 174,
 175,
 176,
 178,
 180,
 181,
 184,
 186,
 187,
 188,
 190,
 191,
 192,
 193,
 196,
 197,
 199,
 202,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 214,
 215,
 216,
 218,
 219,
 220,
 221,
 222,
 224,
 229,
 230,
 231,
 232,
 234,
 237,
 238,
 240,
 241,
 243,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 254,
 255,
 256,
 257,
 258,
 260,
 262,
 263,
 264,
 265,
 271,
 272,
 274,
 277,
 278,
 280,
 281,
 282,
 283,
 285,
 286,
 288,
 290,
 291,
 294,
 297,
 299,
 301,
 302,
 303,
 305,
 306,
 307,
 309,
 311,
 312,
 313,
 314,
 316,
 319,
 321,
 322,
 325,
 327,
 328,
 329,
 331,
 333,
 334,
 335,
 338,
 339,
 342,
 343,
 344,
 345,
 346,
 347,
 348,
 350,
 351,
 352,
 354,
 356,
 357,
 358,
 360,
 363,
 364,
 365,
 366,
 368,
 369,
 370,
 372,
 373,
 375,
 376,
 377,
 378,
 379,
 381,
 383,
 385,
 386,
 387,
 388,
 389,
 390,
 391,
 393,
 394,
 397,
 398,
 399,
 400,
 402,
 403,
 404,
 405,
 406,
 407,
 408,
 410,
 412,
 413,
 414,
 416,
 417,
 418,
 419,
 421,
 422,
 423,
 424,
 425,
 428,
 429,
 432,
 433,
 434,
 436,
 437,
 439,
 440,
 441,
 442,
 444,
 445,
 446,
 447,
 448,
 449,
 450,
 456,
 457,
 458,
 459,
 460,
 461,
 462,
 463,
 464,
 468,
 469,
 470,
 471,
 472,
 473,
 475,
 477,
 480,
 482,
 483,
 484,
 485,
 486,
 488,
 490,
 491,
 492,
 493,
 494,
 495,
 496,
 498,
 500,
 502,
 503,
 505,
 506,
 508,
 509,
 512,
 513,
 515,
 517,
 518,
 520,
 521,
 522,
 524,
 525,
 526,
 527,
 528,
 529,
 530,
 531,
 533,
 534,
 539,
 540,
 541,
 542,
 545,
 546,
 547,
 548,
 551,
 552,
 553,
 554,
 555,
 557,
 558,
 559,
 560,
 561,
 562,
 563,
 564,
 568,
 569,
 570,
 571,
 573,
 574,
 575,
 576,
 577,
 578,
 579,
 580,
 581,
 584,
 585,
 587,
 588,
 589,
 590,
 592,
 595,
 596,
 598,
 599,
 600,
 601,
 602,
 603,
 605,
 606,
 608,
 610,
 612,
 613,
 614,
 615,
 616,
 617,
 620,
 622,
 623,
 624,
 625,
 626,
 629,
 632,
 633,
 634,
 635,
 636,
 637,
 640,
 641,
 643,
 644,
 646,
 647,
 648,
 651,
 652,
 653,
 654,
 655,
 656,
 658,
 661,
 663,
 664,
 666,
 667,
 669,
 671,
 673,
 674,
 676,
 677,
 679,
 681,
 682,
 683,
 684,
 685,
 687,
 688,
 690,
 691,
 693,
 695,
 696,
 697,
 700,
 701,
 702,
 703,
 704,
 705,
 707,
 709,
 710,
 711,
 712,
 713,
 714,
 715,
 716,
 720,
 722,
 723,
 725,
 726,
 727,
 728,
 729,
 730,
 731,
 733,
 734,
 735,
 736,
 737,
 739,
 740,
 742,
 744,
 745,
 746,
 747,
 748,
 749,
 750,
 751,
 752,
 754,
 756,
 760,
 761,
 762,
 763,
 764,
 765,
 768,
 770,
 771,
 772,
 773,
 774,
 777,
 780,
 781,
 782,
 784,
 785,
 787,
 788,
 790,
 791,
 792,
 795,
 797,
 799,
 802,
 803,
 806,
 807,
 808,
 809,
 811,
 813,
 814,
 815,
 816,
 819,
 820,
 822,
 823,
 824,
 825,
 826,
 827,
 830,
 831,
 832,
 833,
 835,
 836,
 838,
 839,
 840,
 841,
 842,
 844,
 846,
 847,
 848,
 849,
 850,
 852,
 853,
 855,
 856,
 857,
 859,
 860,
 861,
 862,
 863,
 864,
 865,
 866,
 867,
 868,
 869,
 871,
 875,
 876,
 877,
 878,
 879,
 881,
 883,
 884,
 885,
 886,
 888,
 890,
 891,
 892,
 893,
 894,
 895,
 896,
 897,
 898,
 900,
 901,
 903,
 904,
 905,
 906,
 907,
 909,
 910,
 911,
 912,
 913,
 914,
 915,
 917,
 918,
 920,
 921,
 922,
 923,
 924,
 925,
 927,
 928,
 929,
 930,
 931,
 932,
 933,
 934,
 938,
 939,
 940,
 941,
 942,
 943,
 944,
 945,
 946,
 947,
 948,
 949,
 951,
 953,
 954,
 955,
 958,
 959,
 960,
 961,
 962,
 963,
 964,
 965,
 966,
 967,
 968,
 969,
 970,
 971,
 972,
 973,
 977,
 978,
 979,
 980,
 981,
 982,
 983,
 984,
 985,
 986,
 987,
 989,
 990,
 991,
 992,
 993,
 995,
 996,
 997,
 999,
 1000,
 1001,
 1002,
 1003,
 1004,
 1005,
 1006,
 1007,
 1008,
 1009,
 1010]

In [33]:
total.merge(partner_df3)

,id,age,job,marital,education,balance,housing,loan,default,gender
0,1,26.0,unemployed,married,tertiary,454,yes,yes,no,women
1,2,25.0,technician,married,secondary,517,no,no,no,women
2,3,36.0,technician,single,secondary,1044,yes,no,no,man
3,5,27.0,management,married,tertiary,145,no,no,no,man
4,6,45.0,unemployed,divorced,primary,11,no,no,yes,man
...,...,...,...,...,...,...,...,...,...,...
705,1006,NaN,management,married,tertiary,2071,yes,no,no,women
706,1007,NaN,entrepreneur,married,secondary,-1882,no,no,no,man
707,1008,NaN,unknown,single,unknown,1819,no,no,no,man
708,1009,NaN,self-employed,NaN,secondary,146,yes,no,no,women
709,1010,NaN,services,single,secondary,297,no,no,no,women

In [ ]:
pd.merge(left = pa)